### ISSUE TITLE
Unable to run process unless it's in PATH

### ISSUE THREAD

**Issue by NDavidBrown** [cucumber/aruba#141]
I've tried running a command via  relative path, then by changing to its directory and calling the command name directly. Neither works.

Does Aruba really limit you to PATH binaries only?

It would be good if you add support for setting of childprocess's `process.cwd` so that at the very least binaries in the cwd may be used.

For now the workaround is to pass a relative path to a command executor e.g. `sh -c relPath/script.sh` on UNIX.

**Comment by dg-ratiodata** [comment]
Running a comand with relative path is possible now. Please see https://github.com/cucumber/aruba/blob/master/features/api/command/run.feature#L26 for a full example.

You can also set a default timeout via the aruba timeout step. https://github.com/cucumber/aruba/blob/master/features/steps/commands/exit_statuses.feature + https://github.com/cucumber/aruba/blob/master/features/commands/interactive.feature

**Comment by ebuildy** [comment]
Hello @kwiknik , you can add custom PATH easily, inside ``features/support/env.rb`` :

    ENV['PATH'] = "#{ENV['PATH']}:#{ENV['HOME']}/src"
    require 'aruba/cucumber'
