### ISSUE TITLE
Enabling Aruba reporting causes ActiveSupport to throw error respecting bcat\ansi 

### ISSUE THREAD

**Issue by byrnejb** [cucumber/aruba#170]
This error results from two undeclared gem dependencies - bcat and rdiscount.

Arch = i86_64
OS = CentOS-6.4 (RHEL6)

activesupport (4.0.1)
aruba (0.5.3)
bundler (1.3.5)
cucumber (1.3.10)
pygments.rb (0.5.4)

NOTE: This is NOT a Ruby on Rails project.  It simply uses some of the modules.

This works:
```
bundle exec cucumber -b features/hll_th_forex_rss_fetch.feature
Using the default profile...
```

This does not work:
```
ARUBA_REPORT_DIR=features/report bundle exec cucumber -b features/hll_th_forex_rss_fetch.featurecannot load such file -- bcat/ansi (LoadError)
/home/byrnejb/Projects/Software/theHeart/code/hll_th_forex_rss/libexec/bundler/lib/ruby/2.0.0/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
```

The only difference is ARUBA_REPORT_DIR is set in the second and absent from the first.

**Comment by dg-ratiodata** [comment]
Aruba::Reporting is deprecated and will be removed with 1.0.0. You may want to run your commands in debug mode instead to troubleshoot them https://github.com/cucumber/aruba/blob/master/features/commands/debug_command.feature.
