### ISSUE TITLE
Run command in working @dirs folder

### ISSUE THREAD

**Issue by schickling** [cucumber/aruba#176]
Is there a way to run the specified command in the @dirs folder (`tmp/aruba`)?

When I run my command `myCommand` I want it to be executed in the `tmp/aruba` folder. Currently it gets executed in the folder where `cucumber` is called.

**Comment by dg-ratiodata** [comment]
The working directory is now set for the command executed - https://github.com/cucumber/aruba/blob/master/lib/aruba/processes/spawn_process.rb#L71. Can you please try again. Otherwise please re-open the issue.
