### ISSUE TITLE
Support for complex commands (pipes, backticks, env variables) in steps

### ISSUE THREAD

**Issue by fabn** [cucumber/aruba#182]
I'm having some issues with command escaping in aruba, here are two minimal features that represent my issues:

```gherkin
Feature: Command escaping issues

  Scenario: Failed command with subcommand
    Given a file named "testfile" with:
      """
      foo bar
      """
    When I run `echo $(cat testfile)`
    # When I run "echo `cat testfile`" # also failing
    Then the output should contain "foo bar"

  Scenario: Failing environment in command line
    Given I set the environment variables to:
      | variable | value |
      | FOO      | bar   |
    When I run `echo $FOO`
    Then the output should contain "bar"
```

Is this something that is not supposed to be supported by aruba?

Is there any syntax trick to make these features working?

**Comment by michaelbarton** [comment]
I came across this issue and thought this step snippet might be of use to others who would like to something similar to OP's request.

    When(/^in bash I successfully run:$/) do |string|
        run_simple(unescape("bash -c '#{string}'"))
    end

I use this for multiline bash commands.

**Comment by dg-ratiodata** [comment]
@jarl-dk That snippet above would be something for the `aruba-guide`-thing.

**Comment by jarl-dk** [comment]
@dg-ratiodata : Good point. Thanks...

**Comment by jarl-dk** [comment]
I am closing this as it seems like the discussion has closed.

**Comment by UltimateGeek** [comment]
A pystring-solution for this has been provided with [step "When I run the following (commands|script):"](https://github.com/cucumber/aruba/blob/v1.0.0.pre.alpha.2/lib/aruba/cucumber/command.rb#L29)
