### ISSUE TITLE
'then files should exist' returns false?

### ISSUE THREAD

**Issue by Cheneweth** [cucumber/aruba#183]
Just trying to learn Aruba. Have a simple command line tool that given a file name will create an empty file with that name in the current folder. 

e.g.,
$ create_file filename.txt
will just create an empty file called 'filename.txt' in the working directory. However when I run a simple test like

Scenario: create file
  when I run 'create_file filename.txt'
  then the following files should exist:
    | filename.txt |

returns false. (interestingly when I execute the same cucumber test from within Rubymine ide it succeeds)

**Comment by dg-ratiodata** [comment]
@Cheneweth Please try aruba 0.9.0 and re-open the issue, if the problem still exists for you.
