### ISSUE TITLE
Appending to a file doesn't add newlines

### ISSUE THREAD

**Issue by ashmoran** [cucumber/aruba#2]
I'm working on this, the patch will make it self-explanatory

**Comment by smortex** [comment]
The current behavior does not add a `\n` at end of the last line, however the [definition of a "line"](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap03.html#tag_03_205) explicitly tells that a line should be terminated by a `\n`:

>  3.205 Line
> A sequence of zero or more non- \<newline\>s plus a terminating \<newline\>.

A discussion on the subject can be read on [stackexchange](http://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file).

The current implementation makes it necessary to put a blank lines after the last one if you want it to be "formatted" properly, which is disturbing. Can you please consider reopening this issue?

**Comment by dg-ratiodata** [comment]
Mmh... Although this might be disturbing, it's more flexible since you can generate files where the newlines are missing. For now I don't want to change this behaviour.
