### ISSUE TITLE
Aruba::Api.assert_partial_output_interactive() function name is misleading

### ISSUE THREAD

**Issue by UltimateGeek** [cucumber/aruba#222]
assert_partial_output_interactive() does not use expect(), and therefore does not cause a failure when the text does not match.  Its use by `When I wait for (?:output|stdout) to contain...` needs for it to not fail, so its behavior is ok, but the name of the method is misleading. "Assert" conveys a sense that it will create a failure to occur if the expected condition is not met. Please change the name of the existing method, or adjust the design of the use of it by `When I wait for output to contain` to have it use expect() by default, but when given an optional argument, it suppresses the assertion.

**Comment by dg-ratiodata** [comment]
Those `assert_*`-methods are deprecated and will be removed in 1.0.0. Instead you can you our new matchers: https://github.com/cucumber/aruba/tree/master/lib/aruba/matchers
