### ISSUE TITLE
Refactor API

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/aruba#231]
Hi @jarl-dk  @mattwynne ,

I would like to discuss the following things with you:

1. Move "Helper"-methods to `aruba/helpers.rb` - e.g. `absolute_path`
2. Move internal helpers to `aruba/utils.rb` and make them `module`-functions of `Aruba::Utils`

   '1.' and '2.' will make clear, what is part of the `aruba`-API

3. Migrate `check_*`-methods to `rspec`-matchers
4. Migrate `assert*`-methods to `rspec`-matchers
   
   '3.' and '4.' will make tests more readable + providing better error methods
   to users. And will make use of all the good things which come with
   `expect(x)`. And as we are already using `rspec` for the api-tests,
   testing of the new `matchers` will be dead simple.

   Alternative: Create more custom matchers to improve code.

   *Example*:

   **old**

   ```ruby
   def check_file_size(paths_and_sizes)
     prep_for_fs_check do
       paths_and_sizes.each do |path, size|
         path = File.expand_path(path)
         expect(File.size(path)).to eq size
       end
     end
   end
   ```

   **new**

   ```ruby
   def check_file_size(paths_and_sizes)
     prep_for_fs_check do
       paths_and_sizes.each do |path, size|
         path = File.expand_path(path)
         expect(path).to have_file_size size
       end
     end
   end
   ```

   Writing `rspec` tests using the `assert_*` looks very weird. I would prefer
   to have custom `rspec`-matchers for this.

   **old**

   ```ruby
   def assert_partial_output(expected, actual)
     actual.force_encoding(expected.encoding) if RUBY_VERSION >= "1.9"
     expect(unescape(actual)).to include(unescape(expected))
   end
   ```

   **new**

   ```ruby
   def assert_partial_output(expected, actual)
    $stderr.puts 'Deprecated'
     expect(actual).to include_content expected
   end

   # matcher
   RSpec::Matchers.define :include_content do |expected|
     match do |actual|
       actual.force_encoding(expected.encoding) if RUBY_VERSION >= "1.9"
       
       # Support real files as well
       actual = File.read(absolute_path(actual.to_s)).chomp if actual.is_a? Pathname
       Aruba::Utils.unescape(actual).include? Aruba::Utils.unescape(expected)
     end

     failure_message do |actual|
       format("expected that file \"%s\" has content \"%s\".", actual, expected)
     end

     failure_message_when_negated do |actual|
       format("expected that file \"%s\" does not have content \"%s\".", actual, expected)
     end
   end

  # test for string
  RSpec.describe 'includes content' do
    subject { 'string' }
  
    context 'when includes content' do
      it { is_expected.to include_content 'content a' }
    end
  
    context 'when not includes content' do
      it { is_expected.not_to include_content 'content c' }
    end
  end
  
  # test for file
  # this could made real by wrapping all the magic within a matcher
  RSpec.describe 'includes content' do
    subject { Pathname.new('file') }
  
    context 'when includes content' do
      before(:each) { write_file(subject, 'content a') }
      it { is_expected.to include_content 'content a' }
    end
  
    context 'when not includes content' do
      it { is_expected.not_to include_content 'content c' }
    end
  end

   ```

4. Add convenience-layer for `minitest`-users via `assert_*`-methods
5. Introduce `minitest` and `rspec`-require-files, e.g. `aruba/minitest` and `aruba/rspec`

   * `aruba/rspec`:

     ```ruby
     require 'aruba/helpers'
     require 'aruba/utils'
     require 'aruba/matchers'
     ```

   * `aruba/minitest`:

     ```ruby
     require 'aruba/helpers'
     require 'aruba/utils'
     require 'aruba/assertions'
     ```

**Comment by mattwynne** [comment]
Sounds like steps in the right direction to me. Just remember to keep the PRs small so they’re easy to review.

cheers,
Matt

—
+44 20 8720 6842
Co-founder, Cucumber Limited
matt@cucumber.pro

**Comment by jarl-dk** [comment]
All proposals sounds good. Definitely the right direction... And I agree with @mattwynne make steps in seperate PRs (or merges, now that you've gt the karma)

**Comment by dg-ratiodata** [comment]
Done.
