### ISSUE TITLE
When using Aruba::InProcess and RSpec undefined method `output`

### ISSUE THREAD

**Issue by waterlink** [cucumber/aruba#236]
aruba 0.6.2
ruby 2.1.1p76

Exactly when using `output_from` method:

```
     Failure/Error: @last_output = output_from(command)
     NoMethodError:
       undefined method `output' for #<Aruba::InProcess:0x0000010569c700>
```

This monkey patch as a workaround makes my spec both blazingly fast and green:

```ruby
class Aruba::InProcess
  def output
    stdout + stderr
  end
end
```

Not sure if it is correct in all edge cases but works for me.

Do you want me to create a PR with this new method for `Aruba::InProcess` ? I of course will add specs for this one.

If so, then do you have any suggestions to this implementation? Any edge cases I'm not aware of?

--
KR, Oleksii.

**Comment by mattwynne** [comment]
That sounds useful to me!

**Comment by dg-ratiodata** [comment]
This method is now added along some more. Can you please try again? Otherwise re-open this issue, please.
