### ISSUE TITLE
Add Dennis Günnewig as a core contributor

### ISSUE THREAD

**Issue by mattwynne** [cucumber/aruba#242]
Hi @dg-ratiodata,

I've been really impressed with the amount of care and attention you've been giving to Aruba lately. We'd like to invite you to join the core team.

I would email you but it's private on GitHub. Please join the mailing list at https://groups.google.com/forum/#!forum/cukes-devs and we'll welcome you there!

We could try to arrange a Google Hangout for you, Jarl and I to discuss our ideas for Aruba. What do you think?

**Comment by dg-ratiodata** [comment]
@mattwynne Thanks a lot :smile: Would you mind to add my private account @maxmeyer as well?

**Comment by dg-ratiodata** [comment]
@mattwynne 
I sent you an email from my private mail address a few minutes ago. I do not use Google's services a lot, but if this makes things easier we could do this. :smile:

**Comment by mattwynne** [comment]
I've added @maxmeyer. We can use another video service like http://talky.io/ for our conversation if you prefer.

**Comment by dg-ratiodata** [comment]
Looks good. But it does not like my mic. :smile: Will check this at home. Maybe it works with my private equipment.

**Comment by mattwynne** [comment]
Welcome @dg-ratiodata / @maxmeyer!

**Comment by mattwynne** [comment]
@dg-ratiodata I think it would be helpful for others if you explained the relationship between the two GH accounts in their GH profiles (maybe you could use the name field?). It certainly confused me, as I assumed it was two different people.

**Comment by mattwynne** [comment]
You could also consider using the same avatar for both (with a real, friendly photo of your face :grin)
