### ISSUE TITLE
Logo for aruba

### ISSUE THREAD

**Issue by dg-ratiodata** [cucumber/aruba#262]
Maybe we should create a cool logo for aruba?! @jarl-dk @mattwynne What do you think?

**Comment by mattwynne** [comment]
Sounds good Dennis.

We paid for some branding[1] so we could use that as a basis for a logo, or come up with something original. How were you thinking we’d get the logo designed?

[1] https://github.com/cucumber-ltd/brand <https://github.com/cucumber-ltd/brand>

**Comment by dg-ratiodata** [comment]
Mmmh... I think this depends: Should aruba be "seen" as part of cucumber or a standalone "product"? I think this is the first decision to make.

My first ideas were something with

*  the outline of the Aruba Island + the cucumber logo at the right bottom
* three arrows around the aruba island outlike similar to the rspec logo (write test, run test, implement and re-run)
* three arrows around  `$ cmd$ but with the cucumber colours - BTW I like the green of cucumber very much ;-)

But I'm not a marketing s
