### ISSUE TITLE
Time to release a new gem version?

### ISSUE THREAD

**Issue by tristil** [cucumber/aruba#263]
The last gem release was in January but there's quite a lot of work on master. For example right now the README gives instructions to `require 'aruba/rspec'` in `spec_helper` but this doesn't actually work with the current 0.6.2.

**Comment by maxmeyer** [comment]
I will discuss this with @mattwynne and @jarl-dk but I think after I finished the refactoring we should release the next release.

**Comment by mattwynne** [comment]
I agree - release early, release often.

**Comment by dg-ratiodata** [comment]
Released.
