### ISSUE TITLE
Use development branch for new features

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/aruba#264]
Maybe we should introduce a development branch, otherwise the README on master may contain invalid information.

**Comment by mattwynne** [comment]
I think putting a warning at the top of the readme is sufficient:

WARNING: Aruba is under active development. You’re reading the README for the master branch, which may be out of step with the current production version. Please view the docs on http://www.rubydoc.info/gems/aruba <http://www.rubydoc.info/gems/aruba> for the latest production documentation.

> On 20 Jun 2015, at 23:00, Max Meyer <notifications@github.com> wrote:
> 
> Maybe we should introduce a development branch, otherwise the README on master may contain invalid information.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/cucumber/aruba/issues/264>.
> 


cheers,
Matt

—
+44 20 8720 6842
Co-founder, Cucumber Limited
matt@cucumber.io
