### ISSUE TITLE
Remove Aruba::Reporting

### ISSUE THREAD

**Issue by mattwynne** [cucumber/aruba#276]
AFAIK this was an experiment to generate docs for Cucumber from Aruba. I don't know anyone who uses it, and it adds maintenance overhead (e.g. #275). Unless anyone puts up a good argument, I say we remove it in the next release.

**Comment by maxmeyer** [comment]
:+1: Or replace it by some custom cucumber reporter

**Comment by dg-ratiodata** [comment]
I already removed the documentation for reporting from README.
