### ISSUE TITLE
Confusing post-install message

### ISSUE THREAD

**Issue by myronmarston** [cucumber/aruba#278]
> From aruba > 2.0 ruby 1.9.3-support is discontinued

Should this say `aruba >= 1.0`?  It seems odd to drop support for a ruby version in 2.1, given that it's not SemVer compliant at all and the current version is 0.7.

BTW, I don't see a github tag for the 0.7.x release which makes it hard to navigate to them.  And `History.md` hasn't been updated for those releases.

**Comment by maxmeyer** [comment]
Fixed. But maybe we should no drop support for 1.9.3. @mattwynne

**Comment by maxmeyer** [comment]
@myronmarston Thanks for reporting. Thought I had fixed this already.

**Comment by myronmarston** [comment]
> Fixed.

What was the fix?  The gemspec in your master branch [still has the confusing message](https://github.com/cucumber/aruba/blob/master/aruba.gemspec#L21).

Actually, I'm noticing that 0.7.3 and 0.7.4 have been released but I don't see those tags so maybe you released a fix but didn't push it to github?  Your [History.md](https://github.com/cucumber/aruba/blob/master/History.md) doesn't give any insight into what's in 0.7.3 and 0.7.4, either.

**Comment by maxmeyer** [comment]
Damn..
