### ISSUE TITLE
File permissions are platform specific; tests fail on Windows

### ISSUE THREAD

**Issue by weedySeaDragon** [cucumber/aruba#285]
For both 0.7.4 and 0.8.0 the tests for file permissions in <code>spec/aruba/api_spec.rb</code> are using Unix-platform specific tests. Thus these tests will always fail on Windows platforms.  
From Ruby Core 2.2.2 - File (http://ruby-doc.org/core-2.2.2/File.html) :  

```
In the description of File methods, permission bits are a **platform-specific**  
set of bits that indicate permissions of a file.  

[... paragraph on Unix permission bits...]

On non-Posix operating systems, there may be only the ability to make a file read-only  
 or read-write.  In this case, the remaining permission bits will be synthesized to resemble  
 typical values. For instance, on Windows NT the default permission bits are 0644,   
 which means read/write for  owner, read-only for all others. The only change that can   
be made is to make the file read-only, which is reported as 0444.
```

**Comment by dg-ratiodata** [comment]
Ok. Reading this, it is enough to change the permissions used within the tests to make them pass on windows? Are you willing to send a PR for this as well?

**Comment by weedySeaDragon** [comment]
Yup, I can do a PR.  I'll need help understanding the intent of some of the tests, probably.  The biggest issue will be that Windows just doesn't support the variety of permissions / level of granularity that *nix systems do.  I'll start working and will ask my questions here.

**Comment by maxmeyer** [comment]
Perfect. Maybe it's best you add some feature tests first.

```
mkdir -p features/api/filesystem/
touch features/api/filesystem/which.feature
```

Have a look at `features/api/filesystem/which.feature` for some examples on how to write the tests.

**Comment by weedySeaDragon** [comment]
OK -- I'll be sure to do the features first and have you give them a once-over to be sure I've got it right.

**Comment by dg-ratiodata** [comment]
Perfect.

**Comment by weedySeaDragon** [comment]
So your idea was spot on, @maxmeyer : the tests pass if the file permissions used in the tests are changed to ones that Windows 'understands'. Specifically, changing the tests to use 0644 (or '0644')  will make them all pass.
But if it's important that those particular file permissions are used, then we'll need different tests for Windows.
