### ISSUE TITLE
Windows ENV variables are case-insensitive (but not to Ruby)

### ISSUE THREAD

**Issue by weedySeaDragon** [cucumber/aruba#291]
Windows treats its environment variables without regard to the CASE. That is, in Windows, the environment variable <code>'PATH' == 'Path' == 'PaTh' == 'patH'</code> etc.  Using <code>ENV</code> to query the environment variables from Windows is also case-insensitive.  So: <code>ENV['PATH'] == ENV['Path']</code>

However, once that information is brought into Ruby (e.g. by something like <code>environment = ENV.to_hash</code>, then case matters.  In this case, the keys in <code>environment</code> _are_ case sensitive.  So <code>environment['PATH'] </code> is _not_ equal to <code>environment['Path']</code>

This is causing failure anywhere that ENV['PATH'] is used.  (Specs and features that depend on this all fail under Windows.)  ENV['Path'] = _<the actual path information, according to Windows>_ is what is copied into <code>@environment</code>  But the key used is still 'Path' (mixed case).  But in the rest of the code, the key 'PATH' is used.  Since nothing exists for that key, things don't happen like they should.

I suggest that the use of ENV['PATH'] be isolated (turned in to a method call).  Then any initial case conversion can be done privately (e.g. change things to upper case before any comparison is done with ENV['PATH']).  
I'm not sure where such a method should go.  (I haven't explored it.)

**Comment by weedySeaDragon** [comment]
I see that you just did a major refactoring, @dg-ratiodata , and that you created the Environment class.  This is another platform (OS) dependent item.  So perhaps your Environment class should do some simple delegation to either a WindowsEnvironment (which will handle the case-sensitivity stuff so that it's invisible to everyone else) or a UnixEnvironment (or whatever you want to call the one that is not Windows).

**Comment by maxmeyer** [comment]
The class is a little bit older, actually. It was introduced with 0.7. or 08. And yes that's what I've in mind. :smile:

**Comment by weedySeaDragon** [comment]
I've created a PR for this (#293). With that PR (and the one it depends on: #290 ), all but one of the specs passed.  That one that didn't (Aruba::Api files #expand_path when file_name contains fixtures "%" string..)  needed to have one change:  it was using <code>instance_double('Aruba::Environment')</code>.  But that wouldn't work.  Changing the mock from an <code>instance_double</code> to an <code>object_double</code> did the trick.  ...Except for ruby 1.9.2.  The configuration features are failing with that one. I'm not sure if or how this might have caused that.  
i hope this doesn't collide with anything you're working on.

Using the PR, running the cucumber tests on my system now shows a whole new set of errors (in a good way).  As an example, now I'm getting a whole lot of "Command \"cli\" not found in PATH-variable" -- which means that at least things are getting farther.   :clap:

Let me know what you think of it.

**Comment by mvz** [comment]
@weedySeaDragon I'm going through old issues that were closed by stalebot. Is this issue still relevant? If so, I'll reopen it.

**Comment by mvz** [comment]
This is probably fixed in both 0.14 and master.
