### ISSUE TITLE
Buffered output to stdout causes tests to pass locally but fail on Travis CI

### ISSUE THREAD

**Issue by ddelnano** [cucumber/aruba#296]
The application I am testing is a command line utility that spawns two child processes which both communicate to each other over a socket.  When trying to use the `Then the output should contain: ....` assertion, my tests pass locally however I get no output on my Travis CI builds.  Of the two child processes one of them is a javascript CLI and the other is a php CLI.  For my failing assertions, one of them is related to output not showing up from the javascript process and the other three are from the php process. On the php side I have modified my php.ini settings to not buffer stdout using:

```php
ini_set('implicit_flush', 'on');
ini_set('output_buffering', 'off');
```

and also when printing to stdout:

```php
fprintf(STDOUT, "Text to print");
flush()
```

So my output on the php side should not have any issues but it continues to fail.  The javascript process is an open source project that I have not written myself.  It prints the data to stdout by use of `console.log(data);`

The other interesting thing is I also run PHPUnit tests after my cucumber tests that check for output and those run just fine.  So I am unsure if this is an aruba/cucumber problem or something with my php or javascript cli program but I was hoping someone could point me in the right direction and would greatly appreciate any help.

Here is the travis [ci build](https://travis-ci.org/ddelnano/dredd-hooks-php) and the [github repo](https://github.com/ddelnano/dredd-hooks-php) of the code.

**Comment by dg-ratiodata** [comment]
I had a similar issue with a ruby script. I disabled buffered io on stdout there, but maybe this can help you:

`features/support/aruba.rb`:

```ruby
require 'aruba/api'

Aruba.configure do |config|
  config.io_wait_timeout = 15
end
```

**Comment by ddelnano** [comment]
Will aruba know to execute the files in the `support` directory?  I just dropped that file in there as is and my build still failed.  It took a few minutes longer than normal so I think it got the configuration but I just want to make sure.  Also I am using aruba 0.8.

**Comment by dg-ratiodata** [comment]
No, it's a `cucumber` thing which loads the `.rb` files. Add `$stderr.puts Hello World` to that file. If you can see this, the file is loaded. You can also add `@announce` to your feature test, to get more information.

```cucumber
Feature: Blub
  @announce
  Scenario: asdf
    Given
```

Another possibility would be to set a longer exit timeout, but I don't thinks this will help:

```ruby
Aruba.configure do |config|
  config.exit_timeout = 15
end
```

**Comment by ddelnano** [comment]
Sorry I was confused on what aruba's and cucumber's roles are.  I added that print to stderr and I definitely get that output.  However my tests are still failing even after adding the `config.exit_timeout = 15`.

**Comment by dg-ratiodata** [comment]
What did you get from the `@announce`-tag? Can you paste it here?

**Comment by ddelnano** [comment]
The output of the test results can be seen [here](https://travis-ci.org/ddelnano/dredd-hooks-php/jobs/72025746).  

For my scenarios I had the `@debug` tag beforehand on the scenarios.  I have no idea what this does but they were already there from the open source project I was given so I left them there.  Here is one of my [.feature files](https://github.com/ddelnano/dredd-hooks-php/blob/master/features/multiple_hookfiles.feature).

**Comment by dg-ratiodata** [comment]
Oh... `@debug` changes the ProcessLauncher internally. This does not have any stdout/stderr and is meant for interactive debugging via some debugger, e.g. `pry, byebug` on ruby. Please remove this and try again. Please also change from `@announce-output` to `@announce` to really output everything.

**Comment by ddelnano** [comment]
Ah that fixed my issue!! All tests are passing now!  Thank you so much!

**Comment by dg-ratiodata** [comment]
No problem. You're welcome.
