### ISSUE TITLE
Improve `which` for UNIX and Non-unix enviroments

### ISSUE THREAD

**Issue by dg-ratiodata** [cucumber/aruba#297]
`which` is not a suitable name as it's to Unix-specific. Let's use something different, e.g. `expand_command` similar to `expand_path`.

To implement this, we could use code like this

``` ruby
class WindowsPlatform
  def expand_command(program, path = ENV['PATH'])
    Platform::WindowsCommandExpander.new(path).expand(program)
  end
end
```

``` ruby
class UnixPlatform
  def expand_command(program, path = ENV['PATH'])
    Platform::UnixCommandExpander.new(path).expand(program)
  end
end
```

I'm not sure where to move the created files best, maybe under
`lib/aruba/platform/windows_command_expander` and then create another file
`lib/aruba/platform/unix_command_expander.rb`?

Then create some classes:

``` ruby
class UnixCommandExpander
  private

  attr_reader :path

  public
  def initialize(path)
    @path = path
  end

  def expand(program)
  end
end
```

``` ruby
require 'aruba/platform/unix_command_expander'

class WindowsCommandExpander < UnixCommandExpander
  private

  attr_reader :path

  public

  def initialize(path)
    @path = path
  end

  def expand(program)
  end
end
```

**Comment by mattwynne** [comment]
I'd probably put them both in the same file for now. You could even put all the commands in the same file for the time being. Try and find a common protocol / interface for all of the commands - maybe just use `#call`
