### ISSUE TITLE
use conditional filters in RSpec tests to handle OS, Ruby Engine differences

### ISSUE THREAD

**Issue by weedySeaDragon** [cucumber/aruba#301]
There are a number of places in the RSpec tests that are specific to a unix system and will fail on Windows because Windows doesn't implement that feature.  Instead of trying to come up with tests that will satisfy both Windows and "not Windows" operating systems, we should do what RSpec does with its testing:  use **conditional filters**.  
We could define some constant in `spec_helper.rb` that will tell us if the system is running on a Windows OS, like `WINDOWS = FFI::Platform.windows?`.  Then we can use `:unless => WINDOWS` to run specs that should only be run on non-Windows systems, and `if => WINDOWS` to run the test that should only be run on a Windows system.  

Here's an example of how it can be used:  

``` ruby
# in spec_helper.rb:
WINDOWS = FFI::Platform.windows?
```

``` ruby
# in spec\aruba\aruba_path_spec:

  describe '#blocks', :unless => WINDOWS do  
    let(:new_path) { expand_path('path/to/file') }

    before(:each) { FileUtils.mkdir_p File.dirname(new_path) }
    before(:each) { File.open(new_path, 'w') { |f| f.print 'a' } }

    it { expect(path.blocks).to be > 0 }
  end
```

The above example group will fail on Windows, because `.blocks` will always return `nil` since it's not implemented on Windows.  
There are quite a number of tests that will need this.  _File permissions_ is one area where there will need to be different tests for sure.  There may be some other file or directory related tests where this is needed.  

What do you think of using this approach?

**Comment by mattwynne** [comment]
It’s OK, but I’d prefer to minimise the differences as much as possible, then make the few that have to exist really stand out. I think it needs to be obvious to our users which behaviours they can expect to be able to use on all platforms so they don’t end up building test suites they themselves can’t run on Windows.

Maybe these features like `#blocks` should be pulled out into some kind of contrib library that you have to explicitly opt-in to use?

A side point, but where there’s an unimplemented feature, throwing a NotImplemented exception is much more assertive than quietly returning nil.

**Comment by mattwynne** [comment]
I guess doing this is a good first move, because it helps us to see where the differences are, and get a green build on Windows. Then we can decide whether to peel these features off into an opt-in module or something.

**Comment by weedySeaDragon** [comment]
I agree with your points, @mattwynne:  It is better to explictly throw an Exception in these cases..(How many times in your life have you had to check for ```<blah>.nil?```  and then  do some kind of ``rescue NotImplementedError`` ?)  The example I gave is what ``File.blocks`` actually does.  But we can be sure to check for that  -- or whatever is equivalent to "doesn't work on this platform" -- and raise an Exception as needed.  

I do view this as a first move so that it's clear during aruba development where things either diverge because the platforms actually have different abilities/behaviours, or where tests are too unix-specific.  The latter case is a matter of coming up with better tests (now that the requirements have changed to better include Windows).  And as you've mentioned, a strategy (or -ies) can be adopted to clearly and cleanly handle different abilities for different platforms.   (Maybe there won't be that many so the solution can be straightforward. )

**Comment by maxmeyer** [comment]
Just read over the discussion. I need to read it again, but I'm open to add something like 

```ruby
RSpec.describe 'Blub', platform: [:windows] do
end
```

I'm definitly against using constants for that. It took me quite a while to get rid of them via `Aruba.configure` in aruba. In some other projects I'm involved in, it was hard to get rid of them as well: Refactoring was not that easy. Nowadays I prefer to use `Symbols` for that. Those are easy to use, and the logic behind such a thing is easy "to refactor".

**Comment by weedySeaDragon** [comment]
I'm not talking about using constants in the implementation code -- just in testing in order to use RSpec conditional filters.  We can use symbols or the result of a method instead of constants if that's better. No matter whether we use constants or symbols or whatever, it has to work for *example groups and examples* (and maybe even *specific ``expect`` statements).*  The point is that it (1) communicates to the **developers** (you, @mattwynne , me, whomever else) that this test is not appropriate to run on a particular platform (or that this test should only be run on a particular platform), and that it (2) creates a set of tests that will pass on a platform (ex: Windows) by using only tests that are appropriate for that platform.  It's not about the implementation code -- it's only for dealing with testing.  It's a first step in a path towards (1) getting things to run on Windows, and (2) writing platform-specific tests. 

(As a minor point: In this case, I don't think using constants to test for the platform is any worse than using constants to test for the current version of Ruby, e.g. `` if RUBY_VERSION < .....``.   But I totally agree that encapsulating the logic in some way is generally *The Right Thing To Do :tm:* )  

There are a number of other ways we can run platform-specific tests:  Only the tests for the current platform can be loaded (which means the tests need to be refactored so that any platform-specific tests are in separate files).  Or the tests could be generated dynamically (although I'd argue that introduces a level of obtuseness that reduces clarity too much).  Or probably many other ways.  

Here are some examples of how [rspec_core](https://github.com/rspec/rspec-core) handles tests and Windows:  
  * use the ``:unless =>``  conditional filter to run (or not run) an example group:  
    * [rake_task_spec ](https://github.com/rspec/rspec-core/blob/5375dcdfdb5460a51d5003de76eb124997fa26ea/spec/rspec/core/rake_task_spec.rb#L43)  (also see [the following ``context...`` in those tests](https://github.com/rspec/rspec-core/blob/5375dcdfdb5460a51d5003de76eb124997fa26ea/spec/rspec/core/rake_task_spec.rb#L50)
    * [configuration_options_spec](https://github.com/rspec/rspec-core/blob/5375dcdfdb5460a51d5003de76eb124997fa26ea/spec/rspec/core/configuration_options_spec.rb#7)
  * conditionally run an ``expect(...)`` statement if it is/is not on Windows:
    * [using `` expect(...)  if  <something>`` in core_spec.rb ](https://github.com/rspec/rspec-core/blob/master/spec/rspec/core_spec.rb#L233) 
    * [using an ``if <something> expect (...)  else expect(..)`` construct](https://github.com/rspec/rspec-core/blob/5375dcdfdb5460a51d5003de76eb124997fa26ea/spec/rspec/core/bisect/runner_spec.rb#L142)  
  * [use ``before(example)`` to set an example (each example in a group, actually) to pending if it's on Windows](https://github.com/rspec/rspec-core/blob/5375dcdfdb5460a51d5003de76eb124997fa26ea/spec/support/shared_example_groups.rb#L18)

Any of those approaches are valid.  My thought was to just start out with conditional filters as a first step because they're obvious and communicate very clearly to developers. 

Can you explain your implementation more to show me how to use symbols on examples and  example groups to have them run conditionally? I understand how to do it on an entire ``described class`` but not on examples or example groups.

**Comment by mattwynne** [comment]
> On 1 Aug 2015, at 15:57, weedySeaDragon <notifications@github.com> wrote:
> There are a number of other ways we can run platform-specific tests
> 
I say don’t worry too much about the specific technique for turning tests on / off. The hard work here is in picking through the tests and excluding the ones that don’t pass on Windows. We can always refactor the way the check / exclusion is implemented later.
