### ISSUE TITLE
No longer allows to run built binaries with `./`

### ISSUE THREAD

**Issue by atilaneves** [cucumber/aruba#312]
In aruba 0.6.2, this worked:

    When I run `./myapp`

In 0.9.0 it no longer does. I can't add where `myapp` is as part of the `PATH` since the whole point of me using aruba for this particular project is that it's a build system that generates binaries in different places.

**Comment by dg-ratiodata** [comment]
@atilaneves Can you please try 0.10.0.pre? If this doesn't work for you: Is this project of your's OSS? If CI passes I'm going to release 0.10.0.pre2 in the next couple of hours.

With 0.10.0.pre I added a feature test which documents that we support relative paths:
https://github.com/cucumber/aruba/blob/master/features/api/command/run.feature#L26

It's important that the paths put in `run()` are relative to the current working directory `#aruba.current_directory`.

**Comment by atilaneves** [comment]
Yes, it's OSS, it's [this one](https://github.com/atilaneves/reggae). I changed my Gemfile yesterday to pin the aruba version since otherwise the tests wouldn't pass.

I don't understand the last paragraph: what I was doing and used to work is relative to the current working directory.

I'll see if I have time today to try 0.10.0.pre.

**Comment by dg-ratiodata** [comment]
> I don't understand the last paragraph: what I was doing and used to work is relative to the current working directory.

Sorry. that's what I had in mind.

> I'll see if I have time today to try 0.10.0.pre.

Thanks.

Ok. CI passes. I'm going to release 0.10.0.pre2.

**Comment by dg-ratiodata** [comment]
Released.

**Comment by maxmeyer** [comment]
Please re-open issue, if the problem still occures. Thanks.
