### ISSUE TITLE
unset_bundler_env_vars does not work

### ISSUE THREAD

**Issue by codener** [cucumber/aruba#315]
The issue is: [`Aruba::Api::Rvm#unset_bundler_env_vars` does not actually delete ENV variables, but sets them to an empty string](https://github.com/cucumber/aruba/blob/70278975229dfc2b639d57345d1b87fa25333b92/lib/aruba/api/rvm.rb#L34). Bundler sees the ENV variable and appends it to the current directory, leading to error messages.

Inside a Cucumber step, I'm running:
```
  run_simple 'bundle exec rspec'
```

Bundler does not find the Gemfile *inside* `katapult/tmp/aruba/katapult_test_app` because the ENV variable is an empty string:

```
/home/codener/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/definition.rb:23:in `build': /home/codener/code/katapult/tmp/aruba/katapult_test_app not found (Bundler::GemfileNotFound)
	from /home/codener/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler.rb:155:in `definition'
	from /home/codener/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler.rb:123:in `setup'
```

[Aruba 0.10.0.pre seems to have had a method to delete environment variables](https://github.com/cucumber/aruba/blob/master/History.md), however, I could not find it in master.

Please unset ENV variables properly.

**Versions:**
- Aruba: 0.9.0 (but the link above is taken from master (currently Aruba 0.10)
- Ruby: 2.1.5
- Bundler: 1.10.6

**Comment by codener** [comment]
My workaround to fix this is:

```
  unset_bundler_env_vars
  aruba.environment.clear.update(ENV)
```

**Comment by dg-ratiodata** [comment]
You can find it here: https://github.com/cucumber/aruba/blob/master/lib/aruba/api/environment.rb#L69

**Comment by dg-ratiodata** [comment]
Therefor I'm not going to fix the `aruba#unset_bundler_env_vars`-method. Can you please come back and report if the `delete_environment_variable` works for your use case?

**Comment by codener** [comment]
I've somehow made this work for me without all the workarounds I had. Haven't understood it fully yet.

Nonetheless, thanks for pointing me to that method.
