### ISSUE TITLE
Gems cannot set ENV-variables

### ISSUE THREAD

**Issue by dg-ratiodata** [cucumber/aruba#320]
If a gem used by your project sets ENV['VAR'] this is not honored. Please see https://github.com/middleman/middleman/pull/1679 and https://travis-ci.org/middleman/middleman/builds/90096797 The stylus gem adds `ENV['PATH']` which gets lost.

@tdreyno JFYI

**Comment by maxmeyer** [comment]
@tdreyno I added a fix to aruba's master. I'm waiting for PR to finish green. Then I hope that the stylus problem should be fixed in `middleman`'s code base.

**Comment by maxmeyer** [comment]
See PR #321.
