### ISSUE TITLE
Cannot set fail_on_error with run_simple

### ISSUE THREAD

**Issue by mikepack** [cucumber/aruba#322]
The logic [here](https://github.com/cucumber/aruba/blob/master/lib/aruba/api/command.rb#L271) will always result in `true`. ie:

```ruby
run_simple('cmd', false)
# leads to...
false || true #=> true
```

```ruby
run_simple('cmd', true)
# leads to...
true || true #=> true
```

Sorry, don't have time to submit a PR right now, but wanted to report after upgrading to 0.11.x.

**Comment by dg-ratiodata** [comment]
@mikepack Yeah, thanks. Will have a look at this. Unfortunately I'm a little bit out of time as well. So it may take some time until, I can fix that.

**Comment by mikepack** [comment]
No problem. I worked around it by switching to the option has style:

```ruby
run_simple('cmd', fail_on_error: false)
```

**Comment by dg-ratiodata** [comment]
Ah. Ok. Then it's a bug I introduced with my last changes. Damn.

**Comment by mikepack** [comment]
:beers: thanks for all your work on Aruba!

**Comment by dg-ratiodata** [comment]
:-)

**Comment by dg-ratiodata** [comment]
I hope I fixed the issue in master, can you please verify that?

**Comment by mikepack** [comment]
Fixed!

**Comment by dg-ratiodata** [comment]
Ok. 0.11.2 is out now. Can you check that as well? Thanks a lot.

**Comment by mikepack** [comment]
Works like a charm.

**Comment by dg-ratiodata** [comment]
Great. Thanks for the feedback.
