### ISSUE TITLE
event-bus source code

### ISSUE THREAD

**Issue by wwood** [cucumber/aruba#334]
Hi,

Perhaps this isn't the right venue for this, but I'm attempting to package `aruba` for the GNU Guix package manager, and `aruba` requires `event-bus`. I can download the `event-bus` gem from rubygems without issue, but I am wondering where the source code for this gem is located. The URL listed at rubygems is https://github.com/cucumber/event-bus but this repository 404s for me.

It appears that the `features` and `spec` directories are missing from the gem making testing event-bus from the contents of the gem impossible.

What to do?

Thanks,
ben

**Comment by jasnow** [comment]
Talk to @dg-ratiodata at https://github.com/dg-ratiodata/event-bus

**Comment by wwood** [comment]
Ah, hadn't seen that (didn't google / duckduckgo and wasn't connected in the network graph). Thanks, a satisfying answer.

**Comment by maxmeyer** [comment]
Sorry @wwood for the inconvience. I hope that @mattwynne accepts event-bus as `cucumber`-project. Then all links will work.

**Comment by dg-ratiodata** [comment]
BTW: I changed the links for now pointing to the correct repository.
