### ISSUE TITLE
VERSION in lib/aruba/version.rb is still 0.11.2

### ISSUE THREAD

**Issue by jasnow** [cucumber/aruba#337]
Guess it should be 0.12.0 to match Rubygems' release version.

**Comment by maxmeyer** [comment]
Damn. Thanks. That happens sometimes because `origin` points to my private repository. :-/

**Comment by maxmeyer** [comment]
Pushed the missing commits.

**Comment by maxmeyer** [comment]
Normally I use `bundler`'s rake task which push to `origin`.
