### ISSUE TITLE
io_wait is misconfigured

### ISSUE THREAD

**Issue by kgilpin** [cucumber/aruba#341]
SpawnProcess is using `@io_wait`:

https://github.com/cucumber/aruba/blob/master/lib/aruba/processes/spawn_process.rb#L117

But the variable name is actually `@io_wait_timeout`:

https://github.com/cucumber/aruba/blob/master/lib/aruba/processes/basic_process.rb#L26

**Comment by dg-ratiodata** [comment]
Good catch. Thanks for reporting. Should be fixed by 9cf22ae
