### ISSUE TITLE
Clean up Release Karma

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/aruba#345]
@aslakhellesoy @mattwynne I'm cleaning up the Aruba Project a bit.

Suggestion: Remove relase Karma on rubygems.org for the following users? What do you think?

* dchelimsky https://rubygems.org/profiles/dchelimsky
* msassak https://rubygems.org/profiles/msassak
* tom025 https://rubygems.org/profiles/tom025

**Comment by aslakhellesoy** [comment]
Sure thing - They haven't been active for years. Do you need help with this?

**Comment by dg-ratiodata** [comment]
Thanks. No. I cleaned up owners list.
