### ISSUE TITLE
Master still uses Utils instead of Aruba.platform

### ISSUE THREAD

**Issue by e2** [cucumber/aruba#346]
## Summary

Utils isn't defined anywhere anymore:

https://github.com/cucumber/aruba/blob/3c46eecb32b9768a014b29f2b925510e8b0c9074/lib/aruba/platforms/command_monitor.rb#L105

## Possible Solution

Use `Aruba.platform.detect_ruby` instead.

**Comment by maxmeyer** [comment]
Thanks for reporting this! Would you mind to send me a PR to fix this?
