### ISSUE TITLE
Create issues for all undocumented aruba API methods

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/aruba#367]
## Summary

Let's create an issue for each method which has no documentation / acceptance test.
## Expected Behavior

We have got a single issue for each method which has no documentation / acceptance test. We flag easier ones with `contributors/first-timers` to make it easier for users to get involved.

## Current Behavior

No one knows which parts are undocumented

## Possible Solution

Try to involve more people to fix this. The first step is to create issues for that.

**Comment by e2** [comment]
:+1:

**Comment by mvz** [comment]
This seems overly redundant. Why not create one issue or some other call-for-documentation? If you really want a list, create one checkboxed list in one issue.
