### ISSUE TITLE
`run` does not support argument array like `Kernel.system`

### ISSUE THREAD

**Issue by e2** [cucumber/aruba#370]
## Summary

You can do `Kernel.system("ruby", "hello.rb")` but in Aruba you cannot do `run("ruby", "hello.rb")`.

(Also, doing so crashes ChildProcess because "hello.rb" is passed as a string for the `:timeout` parameter, which may confuse/discourage users).
## Expected Behavior

I'd expect `run` to work more like `Kernel.system`. Almost related "command running" call in Ruby accepts arguments as method parameters. Also, usually, the first hash is the environment (which can probably be ignored here due to environment setting api) and the last is a hash with options. (Which is how Aruba should expect options for `run` to be passed).
## Current Behavior

`run("ruby", "hello.rb")` crashes (on latest released stable) and definitely doesn't do what Ruby programmers would intuitively expect.
## Possible Solution

Allow command arguments to be passed as an array - just like every developer would expect. Otherwise, the crash is confusing and only more "advanced" users correctly remember to use `Shellwords` to join arguments safely. And it's clumsy to do it manually.
## Steps to Reproduce (for bugs)

Use `run("ruby", "hello.rb")` to crash Aruba with a confusing error.
## Context

As a Ruby developer, I'd expect `run` to work much like `Kernel.system` or `popen`, etc.
## Your Environment

Latest stable Aruba. (0.14.1).

**Comment by dg-ratiodata** [comment]
Additionally I would like to merge `run` and `run_simple` and make it just an argument. So the user does not need decide which to use anymore.
