### ISSUE TITLE
`run` vs `run_simple` are not documented properly

### ISSUE THREAD

**Issue by e2** [cucumber/aruba#371]
## Summary

It isn't clear anywhere how `run` and `run_simple` are different.
## Expected Behavior

I'd expect the different to be clearly documented somewhere.
## Current Behavior

Currently, `run_simple` is used in Cucumber steps. Technically, RSpec users should usually use `run_simple` unless they want to run something interactively. (`run_interactively` used to be more intuitive).
## Possible Solution

Ideally rename `run` to `run_in_background` (or something as suggestive) and rename `run_simple` to `run_and_wait` to at least avoid confusing the two methods. I'd actually make `run` work like `run_simple` does now - if people mistakenly try to "interact", they'll get an error anyway.
## Context

Accidentally using `run` for a simple script produces no output. The results can't be more confusing: no output, nothing announced, no errors. And you really have to dig deep into the api to find out you called `run` instead of `run_simple`. The docs on both methods don't even clear up the confusion. The only meaningful "difference" is that `run_simple` calls `command.stop`.

That's as insanely "non-intuitive" as you can get.

**Comment by maxmeyer** [comment]
I agree, that's hard to see the difference.

**Comment by mvz** [comment]
These methods have now been renamed to `run_command` and `run_command_and_stop`. The documentation is not completely clear yet.

**Comment by roschaefer** [comment]
Please release soon, the documentation might be in sync with `master` but obviously not with the current release. I followed https://app.cucumber.pro/projects/aruba/documents/branch/master and chose to setup aruba with `rspec`. I got

```
     Failure/Error: before { run_command('aruba-test-cli file.txt') }
     NoMethodError:
       undefined method `run_command' for #<RSpec::ExampleGroups::....
```
and I thought: What? :astonished: The quickstart documentation does not work?

Until I searched for `run_command` and found this issue.

**Comment by mvz** [comment]
We should probably
* Clearly state in the master README that the documentation is for master
* rename the branch 'still' to something that makes it clear that that is the branch to look at for 0.14.x.

@maxmeyer what do you think?

**Comment by mvz** [comment]
Hm, the first point is basically done. The second still stands, though.

In the mean time, @roschaefer please look at https://app.cucumber.pro/projects/aruba/documents/branch/still.

And .. we should probably put in the `still` README that it is the documentation for 0.14 😄 .

**Comment by roschaefer** [comment]
@mvz yep, I found that out after posting my comment. I would suggest to point all the documentation in the README on the Github page to the `still` branch (how about the name `released`?).

Usually, I install gems via `gem install` or `bundle install`. If I visit the Github page to find a link for the API documentation, I would expect to see the latest release by default. If I configured a version, e.g. `gem 'aruba', git: 'https://github.com/cucumber/aruba.git'` I would intuitively look for a dropdown menu on the API documentation to switch to the `master` branch (which is already there).

**Comment by maxmeyer** [comment]
> Clearly state in the master README that the documentation is for master

I added this statement to the README some time ago:

~~~markdown
This is the latest version of our README.md (Branch: "master"). There is also the README of the latest released version of "aruba" (Branch: "still").
~~~

I think the problem is, that you/me as a user tries to find information using Google and overread the comment at the very beginning. It's nothing you expect I suppose.

@roschaefer Would you mind to add a PR to add a similar information to the README of the still branch.

@mvz Maybe we've got to many other branches in our "branch list", that one would even oversaw that 0.14 branch. Anyway we can try to rename `still` to something else. The intention behind the naming was to have a more generic branch name we can reuse, but I see the confusion this causes.
