### ISSUE TITLE
Prevent duplicating stderr/stdout for `run_simple` commands

### ISSUE THREAD

**Issue by e2** [cucumber/aruba#374]
## Summary

When stderr+stdout announcing is enabled for `run_simple` in RSpec, both announcements are duplicated.

E.g. if a cli command outputs "hello world" in STDOUT, you'll see:

```
<<-STDOUT
hello world
STDOUT

<<-STDOUT
hello world
STDOUT
```
## Expected Behavior

If the command is only run once, it should print each stderr/stdout announcement only once.
## Current Behavior

Currently, the `stop()` call in `run_simple()` sends the notifications to announce the process's stderr+stdout. Then, `stop_all_commands` does the same.
## Possible Solution

The sanest "workaround" for now is: just temporarily disable announcing during the `stop` in run_simple. Since the output is gathered when the process ends anyway, this isn't a problem.

I implemented this in my own fork here:

https://github.com/e2/aruba/commit/c540485da24c71c1ad6fc3960b6211175e169943

Ideally, there should be a way to "consume" stderr/stdout during announcements. And ideally there would be a "streaming" of stderr/stdout live while the app is running.
## Steps to Reproduce (for bugs)
1. Aruba + RSpec
2. Activate announcing for `stdout`
3. `run_simple` with a simple 'hello world' script
4. You'll have the announcement appear twice (once for `stop` inside `run_simple`, and once for `stop_all_commands` when the test is done)
## Context

I want to see the output of commands - and it's annoying to get errors showing up multiple times on the screen. Especially annoying is having two sets of stdout+stderr. No to mention it's very confusing. (At first I though somehow the test ran twice).
## Your Environment

Project without cucumber (RSpec only, standard setup with `aruba init --test-framework=rspec`).

**Comment by maxmeyer** [comment]
I see. Good that you find the reason. Let me think about that one. Maybe we should an option to silently stop a command. WDYT?

**Comment by e2** [comment]
No, I don't think that would be useful. Users don't know that the output is announced during stop. It's too low level to know about it. 

Just think of Ruby's backticks syntax to execute and capture output - it's simple and understandable with no options. There's no "double output" or silencing option. The same with popen and open3 - the fact that commands are stopped and streams are closed are almost invisible to the user. 

What should happen instead is: Aruba should provide aggregated and partial output at all times. E.g. "announce-aggregated-stdout" would be the equivalent of what it does not. For short-running "run_simple" commands, you only want the aggregate anyway. (at least until Aruba supports live/real-time output in the future output).

E.g. The docker-api gem allows capturing and streaming out live output.

So this is a decent fix until then.

**Comment by jrab89** [comment]
I've noticed this too. For example, when running `echo.feature`:

```
Feature: echo

  @announce-stdout
  Scenario: With 'something' as input
    When I successfully run `echo something`
    Then the output should contain "something"
```

I get this:

```shell
$ cucumber features/echo.feature
Feature: echo

<<-STDOUT
something

STDOUT

<<-STDOUT
something

STDOUT

<<-STDOUT
something

STDOUT

  @announce-stdout
  Scenario: With 'something' as input          # features/echo.feature:4
    When I successfully run `echo something`   # aruba-0.14.1/lib/aruba/cucumber/command.rb:27
<<-STDOUT
something

STDOUT

    Then the output should contain "something" # aruba-0.14.1/lib/aruba/cucumber/command.rb:159
<<-STDOUT
something

STDOUT

<<-STDOUT
something

STDOUT


1 scenario (1 passed)
2 steps (2 passed)
0m0.121s
```

aruba 0.14.1
cucumber 2.4.0
rspec 3.5.2

**Comment by dg-ratiodata** [comment]
Hi @jrab89 can you try to use the branch `still` and see if it's fixed by fff944bd142d558b68b0745b5506495e2ce6fd78. I backported a fix from master. If your answer is yes, I'm going to release 0.14.3 with this fix.

**Comment by jrab89** [comment]
Using aruba from the `still` branch I'm getting

```
$ cucumber features/echo.feature                                                                                                                                                     
Feature: echo

<<-STDOUT
something

STDOUT

<<-STDOUT
something

STDOUT

<<-STDOUT
something

STDOUT

  @announce-stdout
  Scenario: With 'something' as input          # features/echo.feature:4
    When I successfully run `echo something`   # aruba-0.14.2/lib/aruba/cucumber/command.rb:27
<<-STDOUT
something

STDOUT

    Then the output should contain "something" # aruba-0.14.2/lib/aruba/cucumber/command.rb:159

1 scenario (1 passed)
2 steps (2 passed)
0m0.119s
```

**Comment by mvz** [comment]
This was fixed in the stale branch, but is potentially still a problem in master.

**Comment by mvz** [comment]
Waiting for #517...
