### ISSUE TITLE
Feature request: docker support

### ISSUE THREAD

**Issue by e2** [cucumber/aruba#378]
## Summary

Currently, Aruba uses the host's resources for isolating (environment setting, tmp folder) while instead, all this can be done inside a Docker container or VM.

Given Aruba's existing API, it should be transparent whether commands are run on a host OS or inside a VM/container. E.g. `write_file`, `chmod` would all be executed within the "current" Docker container.

## Expected Behavior

Ideally, I should be able to set the "platform" to "Docker" (or something similar) so that all Aruba API commands would be Docker-aware.

E.g. `set_environment_variable` would simply pass the variables to the container running the command. A Cucumber's Background scenario would commit an intermediate docker container image - which could be reused by other scenarios. The `working_directory` feature would map to Docker's `working_directory`.

In fact, most of Docker's Dockerfile commands already can be mapped logically to most of Aruba's API.

## Current Behavior

Currently, Aruba doesn't allow any integration - it gets in the way more than it helps. E.g. ChildProcess cannot be replaced easily with something like `docker-api` (which provides a lot of similar functionality).

There are also not enough "hooks" to "add" such integration - there would be too much monkey-patching.

## Possible Solution

Mostly, the existing API would have to be redesigned for more flexibility and abstraction. This is a good thing, because the outcome would really put the current architecture to the test.

Just "wrapping" calls inside Cucumber steps isn't enough - Aruba has to internally be able to fully communicate with Docker via the Docker API.

## Steps to Reproduce (for bugs)

1. Take an existing Aruba project
2. Try to make the environment setup and commands run flawlessly from within a Docker container

There could be a separate `aruba-docker` project, but it doesn't make sense to develop it until Aruba can actually use such an extension first.

## Context

In general, docker support would allow full-isolation without the current downsides of Aruba/Cucumber, which are:

1. Very slow tests (Docker calls can be really fast since very Background scenario can be cached)
2. Host OS needs to be setup for isolation (While you can set up the guest OS/container without any changes on the host OS)
3. Host OS environment has to be cleared (while inside docker there's a "blank slate", e.g. you can have no dependencies installed)
4. Parallel running is tricky (while all docker containers are independent by design)
5. General "dislike" for specialized "clean room" features, such as RVM support (while inside docker you can just put the OS in any state you want without much effort)
6. No tools for debugging failures (while Docker has lots of feature that can help - e.g. history of commands, snapshots, diffs, tar snapshots, attaching to running containers, etc.)
7. Inconveniences using files from the source tree (while Docker can either copy or use the workspace inside a container)
8. No first-class support for fixtures (while in Docker, a container pretty much IS a fixture).

**Comment by jarl-dk** [comment]
This sounds like a great idea... However I think these ideas with docker should/could be taken into cucumber execution in general. Docker opens many opportunities. It could also be a way to achieve parallel execution in cucumber generally (on a server/container farm).

**Comment by e2** [comment]
@jarl-dk -

> However I think these ideas with docker should/could be taken into cucumber execution in general.

That's my point, basically. Docker is a natural "fit" for what the cucumber format expresses. (scenarios as layers, background scenarios as base images, steps as commands).

Of course it makes more sense in Aruba because running commands takes quite long. Especially with waits/timeouts.
