### ISSUE TITLE
aruba can not find file in bin/ directory

### ISSUE THREAD

**Issue by bdrust** [cucumber/aruba#379]
I am trying to write some tests for a gem that deploys a simple CLI application but the following fails with the below error:
```
Scenario: Display -h output
    When I successfully run `test_cli -h`
    Then the output should contain "this is the -h output"
```
-------------------------------------
```
Scenario: Display -h output              # features/test_gem.feature:8
    When I successfully run `test_cli -h` # aruba-0.14.1/lib/aruba/cucumber/command.rb:27
      undefined local variable or method `cmd' for #<Aruba::Processes::SpawnProcess:0x00000002bce100> (NameError)
```
For some reason it can't find test_cli in the bin/ directory but if I use the full path then the test passes.

**Comment by maxmeyer** [comment]
@bdrust Can you try master? This should be fixed by @e2 in #357.

**Comment by bdrust** [comment]
That fixes the issue for me, thanks.

**Comment by duckinator** [comment]
Are their any plans to release a version that addresses this soon? I have to use master to get around it atm.

**Comment by dg-ratiodata** [comment]
The next milestone would be 1.0.0. Unfortunately I've not much time to work on aruba, but feel free to help out by working on those issues: https://github.com/cucumber/aruba/milestone/4 To make a release soon.
