### ISSUE TITLE
Possible bug: Aruba Cuke steps won't fail when called from other steps

### ISSUE THREAD

**Issue by danascheider** [cucumber/aruba#380]
## Summary

I am using Aruba with Cucumber to test a command line tool that generates code. In most of my features, I need to call Aruba step definitions from within my own step definitions. Although the Aruba steps work fine when not called from another step def, when I do call an Aruba step from inside another step def, the expectations will not fail. I'm not sure whether this is a bug or expected behavior, so I wanted to check before working on a PR. 

## Expected Behavior

In many of my test files, I am using steps like this:
```cucumber
Given a file named "foo.raml" with:
  """
  #% RAML 0.8
  ---
  # generated code
  """
When I run `rambo foo.raml`
Then there should be a file named "foo_spec.rb" with:
  """
  describe Foo do
    # generated code
  end
  """
```
These steps do work as expected. However, it becomes cumbersome to include long content as a docstring, so I would like to write steps like this:
```cucumber
Given a file named "foo.raml" like "basic_raml.raml"
When I run `rambo foo.raml`
Then the file "foo_spec.rb" should be like "basic_raml_spec.rb.example"
```
This step then has the following definition:
```ruby
Given(/^a file named "([^"]*)" like "([^"]*)"$/) do |file, example|
  # The read_example method finds a file named basic_raml.raml in the 
  # /features/support/examples directory and reads from that file.
  text = read_example(example)
  steps %Q{
    Given a file named "#{file}" with:
      """
      #{text}
      """
  }
end

Then(/^the file "([^"]*)" should be like "([^"]*)"$/) do |file, example|
  text = read_example(example)
  steps %Q{
    the file "#{file}" should contain:
      """
      #{text}
      """
  }
end
```
My expectation is that this scenario behave the same as the one using the Aruba-defined steps only. In other words, it should pass if the contents of the output file match those of the example file and fail if they do not.

## Current Behavior

Instead of failing when the contents of the output file do not match those of the example file, the steps that call the Aruba definitions pass regardless of the contents of the output file. (They will fail if the example files don't exist.) Inspecting the contents of the `tmp/aruba` directory confirms that the steps are passing whether the output matches the example or not. 

## Context

This issue is making it very difficult to test this tool with Cucumber, and has resulted in my accepting pull requests that broke the code without realizing it. Although I'm willing to dig into this and make a pull request, I mostly wanted to confirm that this was a bug and not an expected behavior before I did so.

## Your Environment
* Version used: 0.14.1
* Cucumber version used: 2.3.3
* Operating System and version: OS X 10.10.5 Yosemite
* Link to your project: https://github.com/danascheider/rambo

**Comment by dg-ratiodata** [comment]
@danascheider Thanks for providing that much helpful information!

Puh... Really I don't know why this fails. I think this could be a bug. I use the steps in some of my "internal" projects as well, but I think I use the `step`-method not the `steps` one (mind the missing "s"). Can check if this is working as expected?

**Comment by danascheider** [comment]
@dg-ratiodata: The issue there was that using `step` didn't let me include the docstring, which kind of defeated the purpose.

**Comment by maxmeyer** [comment]
@danascheider Does this help? https://github.com/fedux-org/proxy_rb/blob/187df938d5e1d49d965c5c2498932bdb0413d010/features/step_definitions.rb#L11

~~~ruby
Given(/^a feature file named "([^"]*)" with:$/) do |path, content|
  step %(a file named "#{File.join('features', path)}" with:), content
end
~~~

That's what I normally do when using the step-method.

**Comment by danascheider** [comment]
Yeah, I'll try that. I wasn't aware of that syntax.

**Comment by maxmeyer** [comment]
You're welcome. Please close this issue if it's working for you. Thanks.

**Comment by maxmeyer** [comment]
BTW: I think you can even pass a "cucumber table".

**Comment by danascheider** [comment]
OK, so when I try it that way, it gives me <pre><code>Given a file named "foo.raml" like "basic_raml_with_example.raml" # features/step_definitions/file_steps.rb:1
  Undefined dynamic step: "Given a file named "foo.raml" with:" (Cucumber::UndefinedDynamicStep)
  ./features/step_definitions/file_steps.rb:3:in `/^a file named "([^"]*)" like "([^"]*)"$/'
  features/modify_spec_helper.feature:4:in `Given a file named "foo.raml" like "basic_raml_with_example.raml"'</code></pre>

**Comment by maxmeyer** [comment]
Mmh, I cloned your repository and tried to reproduce this. Unfortunately I was not able to reproduce it. Can you please verify PR https://github.com/danascheider/rambo/pull/13 I send you?

BTW: There's also a step in `aruba` to use fixtures - https://github.com/cucumber/aruba/blob/master/features/steps/filesystem/fixtures.feature.

~~~cucumber
Feature: Fixture
  Scenario: Fixture
    Given I use a fixture named "fixtures-app"
    Then a file named "test.txt" should exist
~~~

This requires you to have directory named "fixture" either in <project-root>, features/, spec/. If you want to use it in your specs as well look for the `#copy`-method in here https://github.com/cucumber/aruba/blob/master/features/api/filesystem/fixtures.feature.

**Comment by danascheider** [comment]
Cool, that worked, thanks! Never been so happy to have my cukes finally fail!

**Comment by maxmeyer** [comment]
You're welcome.

**Comment by mattwynne** [comment]
@danascheider FWIW I have a strong preference for calling the underlying API methods from my steps, rather than going through the `step` method. That's partly because I know that the dynamic step invocation code in Cucumber is kinda gnarly, but it's also just that I like to not have unnecessary layers in the way, especially when something goes wrong.

**Comment by danascheider** [comment]
Yeah, I definitely took that into consideration, @mattwynne. The main issue was that since I'm using other Aruba steps, I didn't want to just reinvent Aruba just because I needed that one step different. Or maybe I'm missing your point, that's always possible!

**Comment by mattwynne** [comment]
For example, the step above where you want to run `Given a file named "foo" with:` from Aruba's step library, you can find the implementation of this step [here](https://github.com/cucumber/aruba/blob/master/lib/aruba/cucumber/file.rb#L32).

Now you know that all you need to do to mimic what this step does is to call `write_file(file, unescape_text(example))` directly. All the methods from `Aruba::Api` are available in your Cucumber step definitions, just like `fill_in` etc are when you use Capybara. So whenever I want to do something bespoke that calls Aruba, I tend to just hit that API directly. I can still use Aruba steps the rest of the time though - best of both worlds!

**Comment by danascheider** [comment]
Ah right. Yeah, OK, I see what you're saying. That's probably a better idea.

**Comment by maxmeyer** [comment]
What I would suggest, is something different. What you really use are some kind of fixtures, aren't you?

What `aruba` offers nowadays is:

1. Use our fixture [step](https://github.com/cucumber/aruba/blob/e880f1f7dfe384ef8ec7042fcce085ee17f208a5/features/steps/filesystem/fixtures.feature)
2. Use the [`copy`-method](https://github.com/cucumber/aruba/blob/e880f1f7dfe384ef8ec7042fcce085ee17f208a5/features/api/filesystem/fixtures.feature#L24) which can exapnd `%` (aruba.config.fixtures_path_prefix) in path as fixture path

I see two problem when you decide to use 1.

a. the wording doesn't match your "domain"
b. you cannot passt a different name for the fixture (with the current step def provided by aruba)

if a. is a "problem" and you would like to follow @mattwynne's tip, maybe you want to have a look at [the implementation](https://github.com/cucumber/aruba/blob/e880f1f7dfe384ef8ec7042fcce085ee17f208a5/lib/aruba/cucumber/file.rb#L1). The only thing you need to do is, to create a directory called `<project_root>/fixtures`, `spec/fixtures` or `features/fixtures` and place the files in there.

if only b. is a problem, I'm happy to merge a PR which makes it possible to save the fixture under different name using aruba's fixture step.

Using `copy` there's no need to read the file content. Your step could look like the following one - just written down so the step def can contain bugs.

~~~ruby
Given(/^a file named "(.*)" like "(.*)"$/) do |fixture_name, new_name|
  copy File.join(aruba.config.fixtures_path_prefix, fixture_name), new_name
end
~~~

Aruba will then try to find `fixture_name` in 

~~~
<project_root>/fixtures
<project_root>/spec/fixtures
<project_root>/features/fixtures
<project_root>/test/fixtures
~~~
