### ISSUE TITLE
Merge `run` and `run_simple` into a single method

### ISSUE THREAD

**Issue by dg-ratiodata** [cucumber/aruba#384]
## Summary

Let's merge `run` and `run_simple` into a single method. This also reduces the "danger" for method name conflicts.

## Expected Behavior

Users pass only an argument to `#run` to make it stop and check the command run after a specified amount of time.

## Current Behavior

There are two methods`run` and `run_simple`. The `run_interactive` one has already been removed since `run` was the same.

**Comment by maxmeyer** [comment]
This is not required anymore. We renamed the methods to be more precise what they do.
