### ISSUE TITLE
Remove deprecated code

### ISSUE THREAD

**Issue by dg-ratiodata** [cucumber/aruba#396]
## Summary

There's a lot of code which is deprecated. This causes a lot of deprecation methods. This code should be removed - also see https://github.com/cucumber/aruba/issues/361#issuecomment-217751617.

## Expected Behavior

There should be no deprecations with `aruba` 1.0.0 which destract users of `aruba`.

## Current Behavior

We've got a lot of "active" deprecations in our code base. Those deprecations are announced to users.

## Possible Solution

I see three possible - somehow complementary - solutions:
- Change the way we use deprecations:
  
  Only make them appear before a major release
- Make the activation / deactivation configurable
  
  This may not work everywhere
- Remove deprecated code for 1.0.0

## Steps to Reproduce (for bugs)

1. Run a project using the old methods from aruba
## Your Environment

- Version used: latest
- Operating System and version:
- Link to an example project: https://github.com/middleman/middleman/

**Comment by mvz** [comment]
I'm working on finishing this in #508.

**Comment by maxmeyer** [comment]
@mvz Can we close this one?

**Comment by mvz** [comment]
@maxmeyer Yes.
