### ISSUE TITLE
Compile a list of deprecated methods with alternative

### ISSUE THREAD

**Issue by dg-ratiodata** [cucumber/aruba#397]
## Summary

I would be great / helpful  to have a list where all deprecated methods are listed along with an alternative method given.

## Possible Solution

Create a document where we list all deprecated methods along with their new counterparts. Some more description would be nice. Additionally change deprecation message to link to an entry in the list a user can copy & paste or which is even pasted to stdout.

**Comment by mvz** [comment]
Most deprecation warnings now also show an alternative so this may be less needed.
