### ISSUE TITLE
Generate list of available cucumber steps

### ISSUE THREAD

**Issue by dg-ratiodata** [cucumber/aruba#401]
## Summary

Nowadays it's not easy to find out which steps are provided by aruba.

## Expected Behavior

Have an up to date list of available cucumber steps.

## Current Behavior

Users need to find and read the documentation. Digging documentation is cumbersome and time consuming.

## Possible Solution

Either:
- Add a new method  to the `aruba`-command, e.g. `aruba list steps`
- Add a generator which generates documentation for the aruba steps

## Your Environment

- Version used: latest

**Comment by kisp** [comment]
I believe `cucumber --format​​ ​​stepdefs` will help here.
