### ISSUE TITLE
Cannot find available annotations

### ISSUE THREAD

**Issue by ddelnano** [cucumber/aruba#403]
I have found the documentation for the project very confusing.  I see that there are issues like #400, #401 to improve that but in the mean time I am trying to figure out how to declare a feature to not clear the tmp directory.  I know I have used an annotation `@...` in the past but I cannot remember how I did it and can no longer find where I figured that out.

**Comment by maxmeyer** [comment]
@ddelnano Thanks for reporting this. Is this what you where searching for?

https://github.com/cucumber/aruba/blob/e880f1f7dfe384ef8ec7042fcce085ee17f208a5/features/getting_started/cleanup.feature

**Comment by maxmeyer** [comment]
Yeah, we need to improve the was users can find information.

**Comment by ddelnano** [comment]
@maxmeyer thank you, yes `@no-clobber` was what I was looking for.  Unfortunately its not very user friendly that I need to actually read the source code to figure those things out.  It would be much nicer to have some kind of documentation.  The README basically points to read the source cod.

**Comment by maxmeyer** [comment]
> The README basically points to read the source code.

Yes, actually I would like to improve the user experience in that point. Unfortunately I don't have enough time to do that.

If you like, feel free to improve that by submitting a PR. But I don't want to blow up the README. Maybe it helps to have some kind of a table of contents to point to the right files until we set up a proper documentation.

Alternatively I would like make use of http://www.sphinx-doc.org/en/stable/ which should be used over all cucumbe projects. Would that help you?

Cheers,
Dennis

**Comment by ddelnano** [comment]
@maxmeyer having a Wiki on the Github project could be a good place to prevent the README from becoming large.  I would like to help unfortunately I don't know enough about the project to document it.

**Comment by maxmeyer** [comment]
Mmmmh... Not sure if this is the way I would like to go. The problem with documentation is ...

* needs to make sure that it matches the current implementation
* someone needs to take care about it
* wrong documentation can get unnoticed to long

What do you think about [this](https://github.com/cucumber/aruba#user-documentation) instead. I pushed just a couple of minutes ago. Not that pretty, but we could use our tests as documentation and link to them instead.

**Comment by maxmeyer** [comment]
Seems to be a good compromise between "finding" and "maintaining" stuff.

>  I would like to help unfortunately I don't know enough about the project to document it.

Mmmmh... I can help you to change that, so that you know the project well enough to document things ;-)

**Comment by ddelnano** [comment]
@maxmeyer the problem I have with linking to those `.feature` files is, I am not a Ruby developer.  I used aruba to make PHP and Go cli apps.  So my hope was that the perfect documentation in my mind wouldn't require reading Ruby code.

**Comment by maxmeyer** [comment]
> So my hope was that the perfect documentation wouldn't require reading Ruby code.

So you expect to find documentation somewhere about how to use "our" steps, but not the dsl, correct?

**Comment by maxmeyer** [comment]
I fixed the documentation and restructured things. Do you find it now a easier to find the information you were looking for?

**Comment by ddelnano** [comment]
@maxmeyer yea I thought the "steps" were what this project was used for?  To give an idea of what I was using this project for it was writing tests like [this](https://github.com/apiaryio/dredd-hooks-template/tree/master/features).  So I was looking for what steps, annotations were available, etc.  Yea now that I am looking at the links you added to the README I can see how to see what is available to me now.
