### ISSUE TITLE
interactive commands can prompt for input

### ISSUE THREAD

**Issue by m-mcgowan** [cucumber/aruba#407]
## Summary

When using the `and I wait for the output to contain "abc"` step, the output fetcher tries to wait for the process to exit, which times out when the process is prompting for input. 
## Expected Behavior

Here's a test case:

```
Feature: interactive
  Scenario: running a native binary interactively with multiple prompts
    Given the file named "bin/ask" with:
    """
    #!/bin/bash
    echo -n "What is your name? "
    read name
    echo $name
    echo -n "What is your favorite beer style? "
    read beer
    echo $beer
    echo "Hello $name. I like $beer too! Your round!"
    """
    When I run `bash bin/ask` interactively
    And I wait for output to contain "name"
    And I type "mdma"
    And I wait for output to contain "beer"
    And I type "Belgian Trippel"
    Then the output should contain:
    """
    What is your name? mdma
    What is your favorite beer style? Belgian Trippel
    Hello mdma. I like Belgian Trippel too! Your round!
    """
```
## Current Behavior

When running this, the first `wait for output` step hangs waiting for the process to exit, which it never does, since the process is waiting for input that's provided by the next step. 
## Possible Solution

My quick workaround was to remove the call to stop the process as part of the `have_output` matcher.  https://github.com/cucumber/aruba/blob/master/lib/aruba/matchers/command/have_output.rb#L18-L22

After doing that, the have_output matcher does exit, which then raised a secondary issue in the step definition - `undefined constant ExpectationError` at https://github.com/cucumber/aruba/blob/master/lib/aruba/cucumber/command.rb#L126

I changed that to `rescue RSpec::Expectations::ExpectationNotMetError` and the test above worked.
## Steps to Reproduce (for bugs)

Please run the test above. You'll see it times out after a few seconds with

```
Timeout::Error: execution expired
./features/interactive.feature:15:in `And I wait for output to contain "name"'
```
## Context & Motivation

I am testing a CLI program that prompts the user for information, but currently this doesn't work because the process is expected to exit.
## Your Environment
- Version used: 0.14.1
- Operating System and version: OS X Yosemite
- Link to your project: https://github.com/spark/particle-cli

**Comment by dg-ratiodata** [comment]
@m-mcgowan The step you're using was not meant to be used in a interactive context.

**Comment by m-mcgowan** [comment]
Understood. Any reason to not have this also work for interactive processes?  It seemed like a natural fit from the description.

The implementation changes were trivial, so we could also have an additional flag to not wait for the process to exit, e.g.

`and I wait for the [partial] output to contain "abc"`

where adding `partial` doesn't wait for the process to be complete.

**Comment by dg-ratiodata** [comment]
@m-mcgowan Sorry for the late answer.

I think there were multiple reasons for this:

1. Breaking change of the API
2. Deadlock since programs are not run in background
3. Maybe not supported by all rubies?

Currently I've no time to dig deeper into this. Feel free to put together a PR for this. You're right, that it's a natural fit and really is a missing part.

Before you start: I'm not sure, if this kills other use cases for the library. So this feature would be experimental first to get some real world feedback before we can decide if it can become part of the supported public api.
