### ISSUE TITLE
Where is the actual documentation?

### ISSUE THREAD

**Issue by otheus** [cucumber/aruba#408]
This looks like a nice and very interesting project, especially since I can't find much in the way of testing CLIs directly via rspec. But the documentation is ... unreadable. The few parts that I can read -- in the `.md` files -- seems very incomplete. I can get around in ruby, but new to rspec. If I were wanting to something with `bash`, I'd be completely lost here.

**Comment by dg-ratiodata** [comment]
@otheus 

1. What about this documentation https://github.com/cucumber/aruba#documentation?
2. What do you want to achieve? Testing a CLI app with RSpec or Cucumber?
3. Can you give me an example for "incomplete" documentation?

**Comment by dkniffin** [comment]
I'm also having trouble reading the documentation. It looks to be very complete, but it's all written in the form of cucumber tests. For example, I can't figure out how to actually run my command. I assume the docs for that should be [here](https://github.com/cucumber/aruba/blob/master/features/testing_frameworks/cucumber/steps/command/run.feature), but I don't really know how to read that. There's a lot of setup going on, and I don't really know what I would need to put into my feature file.

**Comment by dg-ratiodata** [comment]
I will see what I can do to improve the situation.

**Comment by a-leung** [comment]
I got Aruba going with RSpec recently and wrote an article about it:

http://redgreenrepeat.com/2016/10/28/testing-hello-world-with-aruba/

Does that help?

**Comment by aptituz** [comment]
Just to add my 50 cents:
What I'd really love to see (as a newbie user), is some kind of getting starting documentation that show-cases basic usage of actual CLI-testing. 

Because as it stands, the README.md documents testing writing to and reading from files (which can be done with plain rspec and plain cucumber), while it should IMHO at least show-case running commands.

Second, I feel like just linking to examples is not really making it easy to get a grip on aruba. Actually I found it so hard, that I ended up implementing a very very very basic aruba-like feature-set myself.

**Comment by maxmeyer** [comment]
@aptituz Our documentation is now on Cucumber.Pro. Can you give it a try? I also setup a getting started repository. The documentation is now part of our README on [Cucumber.Pro](https://app.cucumber.pro/projects/aruba#your-first-tests-with-aruba).

**Comment by maxmeyer** [comment]
Any hints and PRs improving our documentation are highly appreciated!

**Comment by maxmeyer** [comment]
@dkniffin Would you mind to try out the docs given at https://app.cucumber.pro/projects/aruba#your-first-tests-with-aruba? Does this makes sense to you?

**Comment by dkniffin** [comment]
Yes! I haven't used this gem in a while, but that's much better than what I remember.

**Comment by aptituz** [comment]
Agreed. Have not found the Time to actually try it out, yet, but I surely will. Seems promising.

**Comment by maxmeyer** [comment]
@aptituz Did you find the time to have a look?

I'm going to close this one for now. Feel free to open a new issue if have some other suggestions regarding documentation.
