### ISSUE TITLE
Error in setup code for rspec

### ISSUE THREAD

**Issue by otheus** [cucumber/aruba#410]
## Summary

The documentation shows and `init` feature generates code like to be included in `spec/spec_helper.rb`
```
::Dir.glob(::File.expand_path('../support/**/*.rb', __FILE__)).each { |f| require_relative f }
```

This will _not_ work properly if `spec/spec_helper.rb` or said code is in a file, specified to rspec. 

Also, the directory `../support/` is probably incorrect. It should probably be `support/`, ie, a subdirectory under 

## Possible Solution

Replace the documented code and generated code with something like:

```
::Dir.glob(::File.expand_path('support/**/*.rb',File.dirname(__FILE__))).each { |f| require_relative f }
```

## Motivation

For a mixed style project -- which includes CLI and non-cli examples, it's desirable to separate the testing categeories. So in `spec/spec_helper.rb` I have:

```
require `spec/spec_helper_cli.rb`
```

And in that file, I have the `::Dir.glob....` code. This way I can do:

```
rspec spec/spec_helper_cli.rb
```

to test only the CLI related stuff.

**Comment by dg-ratiodata** [comment]
@otheus 

Please place the following code in file named `/tmp/blub.rb` and run it with `ruby`.

~~~ruby
puts ::File.expand_path('../support/**/*.rb', __FILE__)                       # existing code
puts ::File.expand_path('support/**/*.rb',File.dirname(__FILE__))     # suggested code
~~~

You will see, that the current solution and the proposed change produce the same results.

~~~bash
ruby /tmp/blub.rb
# => /tmp/support/**/*.rb
# => /tmp/support/**/*.rb
~~~

Can you please explain in more detail where you see a problem? Don't you like to have a directory called support in your `spec`-directory?

**Comment by dg-ratiodata** [comment]
Feel free to re-open the issue when you find the time to answer. Thanks a lot.
