### ISSUE TITLE
Release a patch update to 0.14.1

### ISSUE THREAD

**Issue by szechyjs** [cucumber/aruba#414]
## Summary

The following commit fixes a bug that prevents running commands with jruby.

https://github.com/cucumber/aruba/commit/9a93bc55df2d1f41be23eb4f6346819f2cfe2a87

However, there has not been a release since this commit. Thus commands with jruby is broken still.

## Possible Solution

Release a patch to 0.14.1

**Comment by dg-ratiodata** [comment]
@szechyjs I pushed some commits to `still`. Will see to release a new (old) version soon.

**Comment by dg-ratiodata** [comment]
Released 0.14.2. Is your issue fixed?
