### ISSUE TITLE
Aruba fails to build proper path when ~ used as path to $HOME

### ISSUE THREAD

**Issue by iiezhachenko** [cucumber/aruba#418]
Log:

>  When I cd to "~"
> /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/childprocess-0.5.9/lib/childprocess/unix/fork_exec_process.rb:26:in `chdir': No such file or directory @ dir_chdir - /home/ubuntu/cloudflare-cli
> /tmp/aruba/~ (Errno::ENOENT)
>         from /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/childprocess-0.5.9/lib/childprocess/unix/fork_exec_process.rb:26:in `block in launch_process'
>         from /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/childprocess-0.5.9/lib/childprocess/unix/fork_exec_process.rb:20:in `fork'
>         from /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/childprocess-0.5.9/lib/childprocess/unix/fork_exec_process.rb:20:in `launch_process'
>         from /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/childprocess-0.5.9/lib/childprocess/abstract_process.rb:82:in `start'
>         from /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/processes/spawn_process.rb:82:in `block in start'
>         from /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/local_environment.rb:22:in `call'
>         from /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/platforms/unix_platform.rb:78:in `with_environment'
>         from /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/processes/spawn_process.rb:81:in `start'
>         from /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/command.rb:67:in `start'
>         from /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/api/command.rb:213:in `run'
>         from /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/api/command.rb:271:in `run_simple'
>         from /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aruba-0.14.2/lib/aruba/cucumber/command.rb:15:in `block in <top (required)>...'

Code
> When I cd to "~"
> And I run `cloudflare-cli dns dump`
> Then the exit status should be 0

**Comment by maxmeyer** [comment]
Sorry for the late reply. Can you please try to mock the home directory first?

**Comment by mvz** [comment]
The code that changes directories looks odd. I'll take a look.

**Comment by mvz** [comment]
The `cd` code assumes only relative paths are used. This seems very limiting.

**Comment by maxmeyer** [comment]
Mmmh... Using `~` should work, but using absolute paths, does not make much sense, as `cd` is more a push/pop-stack if I remember correctly.

**Comment by mvz** [comment]
On the 0.14.x series, you will need to tag the scenario with `@mocked-home-directory`. This will set `$HOME` to the Aruba working directory. You can then remove the line `When I cd to "~"` entirely.

For 1.0.0, I'm planning to make this way of using `cd` work and also always have the home directory mocked to improve test isolation.

**Comment by xtrasimplicity** [comment]
Bump.
