### ISSUE TITLE
turnip support

### ISSUE THREAD

**Issue by munkyboy** [cucumber/aruba#421]
any plans to support [turnip](https://github.com/jnicklas/turnip) ?

**Comment by munkyboy** [comment]
If not, would you be open to a PR to add support for turnip?

**Comment by mattwynne** [comment]
Sure, there's no reason why we can't support other test frameworks. Is it a lot of work to integrate it into Turnip?

**Comment by joeyates** [comment]
@munkyboy I've released aruba-turnip as a separate project with partial implementation of the Aruba DSL.

**Comment by maxmeyer** [comment]
@munkyboy Have nevery used turnip. Did you try to use the RSpec-integration with turnip? You could try to gather some inspiration from https://github.com/cucumber/aruba/blob/master/lib/aruba/rspec.rb and try to send a PR with the integration.

**Comment by maxmeyer** [comment]
@munkyboy Any interest in this? Otherwise I'm going to close this in favor of https://github.com/cucumber/aruba/issues/463.

**Comment by munkyboy** [comment]
sounds good. closing.
