### ISSUE TITLE
Can only change configuration in step definition in deprecated manner

### ISSUE THREAD

**Issue by azgul** [cucumber/aruba#426]
This step definition works (using deprecated way of setting in process class):
```
When(/^I run `([^`]*)` in process$/)do |cmd|
  Aruba.configure do |config|
    Aruba.process = Aruba::Processes::InProcess
    Aruba.process.main_class = VlCli::Runner
  end

  VCR.use_cassette 'cache' do
    cmd = sanitize_text(cmd)
    run_simple(cmd, :fail_on_error => false)
  end

  Aruba.configure do |config|
    Aruba.process = Aruba::Processes::SpawnProcess
  end
end
```

While this one doesn't (not deprecated)
```
When(/^I run `([^`]*)` in process$/)do |cmd|
  Aruba.configure do |config|
    config.main_class = VlCli::Runner
    config.command_launcher = :in_process
  end

  VCR.use_cassette 'cache' do
    cmd = sanitize_text(cmd)
    run_simple(cmd, :fail_on_error => false)
  end

  Aruba.configure do |config|
    config.command_launcher = :spawn
  end
end
```

The underlying reason for me to create a custom step definition rather than letting all commands run in process is because I use `git` in some steps of my tests, which doesn't seem to play nice with in process.

**Comment by maxmeyer** [comment]
Can you please provide an example repo?

**Comment by mvz** [comment]
I can confirm that it doesn't work with the configuration method given. What should work is:

```ruby
aruba.config.main_class = VlCli::Runner
aruba.config.command_launcher = :in_process
```

**Comment by mvz** [comment]
Still planning to work on this, my robotic friend...

**Comment by maxmeyer** [comment]
@mvz The tag "slow burner" prevents the bot to make it "stale".

**Comment by mvz** [comment]
I can confirm that the method described in https://github.com/cucumber/aruba/issues/426#issuecomment-343458570 is the correct method to use in steps.
See the description at the top of https://github.com/cucumber/aruba/blob/061774301c7df545f34cc13e34756ba15374b835/features/02_configure_aruba/basics.feature.
