### ISSUE TITLE
Aruba::API#run conflicts with Minitest#run when included.

### ISSUE THREAD

**Issue by berkes** [cucumber/aruba#435]
## Summary

Including Aruba::API in Minitest is not possible because of a conflicing method `run`.

## Expected Behavior

The test as provided under "Steps to Reproduce" should run and pass without any assertions, failures, successes or errors.

## Current Behavior

It fails with an error, before Minitest even tries to run any tests:

~~~
xxx/gems/aruba-0.14.2/lib/aruba/api/command.rb:140:in `run': Please pass at least a command as first argument. (ArgumentError)
	from xxx/gems/minitest-5.10.1/lib/minitest.rb:822:in `run_one_method'
        .... more backtrace omitted
~~~

When including `Minitest::API` a method `run` is included. Minitest uses a method `run` to run a test. These conflict. The error pasted above is caused because the message signature of `Minitest#run` differs (no arguments) from that of `Aruba`.

## Possible Solution

`Aruba` run could be a class- or instance-method on Aruba. Either `Aruba.run`, `Aruba.api.run` or some such. This way Aruba does not "pollute" the test-class when included with a generic `run` method, but instead has it isolated. Alternative would be to name this method `aruba_run`.

Adding
```
  alias :minitest_run :run
  include Aruba::Api
  alias :aruba_run :run
  alias :run :minitest_run
```
To the TestClass does not work either, because Aruba uses `run` internally, (e.g. in `run_simple`) which now calls `Minitest#run`. 

There might be a ruby trick to include methods of a module in a namespace instead, or prefix them with e.g. a `aruba_` on including. I am not familiar with such a trick.

## Steps to Reproduce (for bugs)

Using the simple test as found below, in e.g. `test/use_aruba_with_minitest.rb`, ran with the command `bundle exec ruby -I test test/use_aruba_with_minitest.rb`:

```
$LOAD_PATH.unshift File.expand_path('../test', __FILE__)

#require 'test_helper'
require 'minitest/autorun'
require 'aruba/api'

class FirstRun < Minitest::Test
  include Aruba::Api

  def setup
    aruba_setup
  end

  def test_it_runs_date
    run_simple("date")
  end
end
```

## Context & Motivation

Using Aruba in Minitest

## Your Environment

> ruby -v
>   ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
> aruba (0.14.2)
> minitest 5.10.1

**Comment by maxmeyer** [comment]
This will be done on "master" as it is a breaking change. Currently we have no release on master, but I will try and release an 1.0.0-alpha.1 next week.
