### ISSUE TITLE
ASCII-8BIT to UTF-8 conversion error on JRuby

### ISSUE THREAD

**Issue by mvz** [cucumber/aruba#477]
## Summary

Running tests on JRuby 9 gives an error when not running in an UTF-8 locale. See https://github.com/cucumber/aruba/pull/476/files#diff-354f30a63fb0907d4ad57269548329e3R43

## Motivation

I'm opening this error so this problem is not forgotten.

**Comment by maxmeyer** [comment]
@mvz Is an issue for the 0.14-branch? I think I merged some PRs to fix this in master.

**Comment by mvz** [comment]
We still have a line https://github.com/cucumber/aruba/pull/476/files#diff-354f30a63fb0907d4ad57269548329e3R64 as a workaround (It seems I'm pointing to the wrong line in the summary above).

I'm not sure at all about the situation on 0.14.

**Comment by mvz** [comment]
Closing this as the workaround has been removed.
