### ISSUE TITLE
Rename #have_same_file_content_like

### ISSUE THREAD

**Issue by mvz** [cucumber/aruba#485]
This matcher name seems grammatically incorrect and unclear: Correct English is 'same as', not 'same like', while the use of 'like' incorrectly suggests a fuzzy or incomplete match.

I'd like to rename this to `#have_same_file_content_as`.

**Comment by maxmeyer** [comment]
Makes sense. Sorry that naming was my fault.

**Comment by maxmeyer** [comment]
Reminder for us: We also need an entry in the CHANGELOG.md for this.
