### ISSUE TITLE
Misleading error message when executing script with broken shebang

### ISSUE THREAD

**Issue by igneus** [cucumber/aruba#501]
## Summary

When execution of a script (via `run_simple`) fails due to a broken shebang (in my case it was formally correct, but pointing to a non-existent executable `/bin/env`), Aruba emits a misleading error message stating that the script doesn't exist.

## Expected Behavior

Instead of falsely claiming that the executable doesn't exist, the error message should state that an attempt to execute it failed. (Possibly with a hint that it might be a shebang issue.)

## Current Behavior

`run_simple "calendariumrom"`

raises

~~~
     Aruba::LaunchError:
       No such file or directory - /home/igneus/src/ruby/calendarium-romanum/bin/calendariumrom
     # /home/igneus/.rvm/gems/ruby-2.3.1/gems/aruba-0.8.1/lib/aruba/processes/spawn_process.rb:68:in `rescue in run!'
     # /home/igneus/.rvm/gems/ruby-2.3.1/gems/aruba-0.8.1/lib/aruba/processes/spawn_process.rb:65:in `run!'
     # /home/igneus/.rvm/gems/ruby-2.3.1/gems/aruba-0.8.1/lib/aruba/api/command.rb:302:in `run'
     # /home/igneus/.rvm/gems/ruby-2.3.1/gems/aruba-0.8.1/lib/aruba/api/command.rb:345:in `run_simple'
     # ./spec/cli_spec.rb:10:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ChildProcess::LaunchError:
     #   No such file or directory - /home/igneus/src/ruby/calendarium-romanum/bin/calendariumrom
     #   /home/igneus/.rvm/gems/ruby-2.3.1/gems/childprocess-0.5.9/lib/childprocess/unix/fork_exec_process.rb:58:in `launch_process'
~~~

Having looked into the backtrace, it is fair to say that the misleading message is not produced by Aruba, but by childprocess. Aruba's fault is "only" blindly believing that childprocess does it's job well.

(I have opened another issue for [childprocess](https://github.com/enkessler/childprocess/issues/123))

## Possible Solution

When handling `LaunchError`, check if the executable exists.

## Steps to Reproduce (for bugs)

1. Create a text file, make it executable, as a first line put a broken shebang, e.g. `#!/bin/this/file/does/not/exist`
2. Try to execute it with Aruba (I did so from within RSpec example with Aruba::Api included)

## Your Environment

* Aruba version used: 0.8.1
* Childprocess version used: 0.5.9
* ruby 2.3.1
* Operating System and version: Linux, distribution Debian Stretch

**Comment by enkessler** [comment]
"Aruba's fault is "only" blindly believing that childprocess does it's job well."

@igneus My motivation to fix this issue is absolutely skyrocketing right now.

**Comment by igneus** [comment]
@enkessler I see. I apologize for this remark. Time for me to pay more attention to the "emotional" part of my writing.

**Comment by enkessler** [comment]
@igneus Apology accepted. To your credit, you still did a great job of documenting and assisting in recreating the error. It is not uncommon that users who open issues on open source projects only provide the 'emotional' and leave out the 'helpful' part entirely. So you are well ahead of the game, in that respect. ;)

Unfortunately and due to the reason that I have since explained over in the related issue on `childproccess`, this behavior is not likely to be changed.

**Comment by igneus** [comment]
This proved to be issue on operating system level, not in aruba or childprocess (see [discussion](https://github.com/enkessler/childprocess/issues/123)). Closing.
