### ISSUE TITLE
Documentation is empty

### ISSUE THREAD

**Issue by jsyeo** [cucumber/aruba#502]
When I go to https://app.cucumber.pro/projects/aruba/documents/branch/master, I only see an empty site with some headers and instructions. The instructions says:

> You can add a cover to you project by adding a Markdown file called features/0/README.md to the project repository.

Is this expected? Where can I find the most up to date docs?

**Comment by maxmeyer** [comment]
Sorry for the inconvience. That was unexpected and is fixed now.
