### ISSUE TITLE
Latest Cucumber fails to see instance var @aruba_timeout_seconds in Before block causing ChildProcess::TimeoutError errors

### ISSUE THREAD

**Issue by matthutchinson** [cucumber/aruba#503]
## Summary

The latest version of Cucumber (anything >2.4.0) fails to see any instance vars e.g. `@aruba_timeout_seconds` set in `Before`  blocks.

## Expected Behavior

No error to be raised, and `@aruba_timeout_seconds` to be respected in each feature.

## Current Behavior

Without `@aruba_timeout_seconds` set, the following error is raised when making a system call (e.g. with back ticks):

`process still alive after 0 seconds (ChildProcess::TimeoutError)`
 or `expected "" to have finished in time (RSpec::Expectations::ExpectationNotMetError)`

E.g. https://travis-ci.org/mroth/lolcommits/jobs/293331478

## Steps to Reproduce (for bugs)

1. Use latest Aruba, with latest cucumber
2. Use a before block like this:
```
Before do                    
  @aruba_timeout_seconds = 20
end
```
3. Create a feature with a step like this: 
```
Given I successfully run `echo "testing"`
```
4. Raises a `ChildProcess::TimeoutError` or `expected "" to have finished in time (RSpec::Expectations::ExpectationNotMetError)`

## Context & Motivation

Use Aruba with the latest cucumber, for [Lolcommits](https://github.com/mroth/lolcommits).

## Your Environment

* Version used: Latest and 0.6.2
* Operating System and version: OSX High Sierra, Travis
* Link to your project: https://github.com/mroth/lolcommits

**Comment by mvz** [comment]
Hi @matthutchinson, thanks for your bug report.

The `@aruba_timeout_seconds` variable is no longer supported on latest Aruba. Please use

```ruby
    Aruba.configure do |config|
      config.exit_timeout = 20
    end
```

**Comment by mvz** [comment]
When using Aruba 0.6.2, you should probably pin Cucumber to a version that works. Please note that 0.6.2 is rather old.

**Comment by matthutchinson** [comment]
Thanks @mvz, I hadn't seen `config.exit_timeout` documented anywhere, I'll try that
