### ISSUE TITLE
Reduce number of labels

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/aruba#506]
## Summary

Reduce the amount of labels for issues. There are many labels. Do we really need them all? @mvz @olleolleolle 

I added most of them - best to my knowledge to that time. What do you think, which of those are neccessary. I added a list of all existing labels as a template.
~~~
* [ ] contributors/first-timers
* [ ] difficulty/easy
* [ ] difficulty/hard
* [ ] difficulty/medium
* [ ] Hacktoberfest
* [ ] needs-feedback/by-community
* [ ] needs-feedback/by-maintainer
* [ ] needs-feedback/by-reporter
* [ ] platform/unix
* [ ] platform/windows
* [ ] status/blocked-by-other-pr
* [ ] status/candidate-for-closure
* [ ] status/needs-more-documentation
* [ ] status/needs-more-tests
* [ ] status/needs-review
* [ ] status/stale
* [ ] status/wont-fix
* [ ] status/work-in-progress
* [ ] type-of-issue/bug
* [ ] type-of-issue/developer-experience
* [ ] type-of-issue/new-feature
* [ ] type-of-issue/refactoring
* [ ] type-of-issue/regression
* [ ] type-of-issue/slow-burner
* [ ] type-of-issue/todo
* [ ] type-of-issue/user-experience
~~~

## Expected Behavior

Maybe we should reduce the amount of labels to make it easier for newcomers. Maybe we should also use the same set of labels as other Cucumber projects.

**Comment by mvz** [comment]
I think most of these labels make sense. The formatting is better in the cucumber/cucumber project though, so I think we should use that: More spaces and colons, less dashes and slashes. For example, we would have `difficulty: medium` and `needs feedback by community`.

* [x] contributors/first-timers
* [x] difficulty/easy
* [x] difficulty/hard
* [x] difficulty/medium
* [ ] Hacktoberfest
* [x] needs-feedback/by-community
* [x] needs-feedback/by-maintainer
* [x] needs-feedback/by-reporter
* [x] platform/unix
* [x] platform/windows
* [ ] status/blocked-by-other-pr

  *We can just mark those as work in progress*

* [ ] status/candidate-for-closure

  *Either means it's stale or it should be closed.*

* [ ] status/needs-more-documentation
* [ ] status/needs-more-tests

  *We can use the GitHub review mechanism for these two, or combine them into a more general `status: needs rework`*

* [x] status/needs-review
* [x] status/stale
* [ ] status/wont-fix

  *Won't fix bugs should just be closed*

* [x] status/work-in-progress
* [x] type-of-issue/bug
* [ ] type-of-issue/developer-experience

  *This one is pretty unclear for newcomers: It kind of sounds the same as user-experience*

* [x] type-of-issue/new-feature
* [ ] type-of-issue/refactoring
* [x] type-of-issue/regression

  *We could combine this one with bug*

* [x] type-of-issue/slow-burner
* [ ] type-of-issue/todo

  *The more internal types developer-experience, todo and refactoring should just be combined.*

* [x] type-of-issue/user-experience

**Comment by mvz** [comment]
GitHub now points new contributors to `help wanted` and `good first issue` labels. We should consider using those.

**Comment by olleolleolle** [comment]
I support @mvz in the use of colons and spaces AND using the GitHub-supported newcomer-supporting labels.

It can be a process of combining, recombining labels, until they support our workflow.

**Comment by maxmeyer** [comment]
@mvz @olleolleolle I reworked the labels.
