### ISSUE TITLE
Retire maxmeyer as maintainer

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/aruba#524]
## Summary

I don't have enought time to support aruba and it's community in a timely manner. I'm not allowed to do open source during business hours and don't have enough time for aruba in my spare time. I hope this might change in the future. But for now I decided to retire as maintainer since I was more or less passive over the course of the last year. Furthermore there's @mvz who does a really good "job" in improving aruba and supporting its community.

TODOs:
* [ ] @aslakhellesoy Please, remove me (maxmeyer, dg-ratiodata) from "aruba-core" and check if @mvz is part of the core group
* [x] @mvz Please, remove me from list of owner at rubygems.org
    * peter_public
    * dg-ratiodata
* [x] @mvz @jarl-dk (j****@****e.dk) is also a owner at rubygems.org, but he's passive for about 1-2 years now. You might want to verify if he still needs the right to push aruba to rubygems.org
* [x] @mvz Verify you've got the right to push the documentation to https://app.cucumber.pro/projects/aruba
* [x] @mvz Verify you're allowed to change aruba's project settings, if not @aslakhellesoy can help you with that.

Besides that:
Thanks @aslakhellesoy, @mvz, @tooky and @mattwynne for your support during the last years! It was a pleasure to work with you. @mvz If there are still questions (in future), don't hesitate to ask.

Thanks.

**Comment by mattwynne** [comment]
@maxmeyer thank you too ❤️  you've done a tremendous job helping Aruba grow up from something that was just extracted out of Cucumber's test suite into a stand-alone open source project. It's been a pleasure working with you, and getting to know you too!

**Comment by olleolleolle** [comment]
@maxmeyer You've been a rock in this process.

Thank you for being here!

(Great "alumni PR", too!)

**Comment by maxmeyer** [comment]
Thanks for all those kind words! I going to be around in community as this is a great "place" to work! And I really loved those community events. 😄 

And I'm still using aruba in a few of my projects.

**Comment by aslakhellesoy** [comment]
Hi @maxmeyer - I just saw this. Thank you so much for all the amazing contributions over the years! I'm familiar with the feeling of guilt of not being able to dedicate enough time to something you're responsible for. Thanks for being honest about it!

I'll go through the checklist as soon as I can.

**Comment by tooky** [comment]
@maxmeyer was amazing to meet you, I hope we'll still see you around the Cucumber community when you have time!

**Comment by mvz** [comment]
@maxmeyer It's a pity we didn't get a chance to work together more. I'll take care of my TODOs in the coming weeks. Hope to see you around.

**Comment by mvz** [comment]
> Verify you've got the right to push the documentation to https://app.cucumber.pro/projects/aruba

I don't think I have this right, but I'm also not sure how to check this.

**Comment by maxmeyer** [comment]
@mvz Can you send me your email address (by slack)? I need that information to add a new collaborator

**Comment by mvz** [comment]
@maxmeyer done!

**Comment by mvz** [comment]
@maxmeyer thanks!

**Comment by maxmeyer** [comment]
@mvz Does it work for you? I think we currently do not have a Github integration to deploy changes to Cucumber Pro automatically. As far as I remember this requires a personal Github token.

**Comment by mvz** [comment]
@maxmeyer yes, I can push to cucumber pro now. Indeed, this is not automated. I do want to see if I can get that part working.

**Comment by mvz** [comment]
I think one TODO is left.

**Comment by mvz** [comment]
@aslakhellesoy can you take a look at the first item on this list please?
