### ISSUE TITLE
@disable-bundler is broken on 1.0 alpha

### ISSUE THREAD

**Issue by doudou** [cucumber/aruba#526]
@disable-bundler is broken (the underlying method has been removed). Not sure whether it is intentional.

The error is

~~~
 undefined local variable or method `unset_bundler_env_vars' for #<Object:0x00000003025be0> (NameError)
 ./aruba/lib/aruba/cucumber/hooks.rb:107:in `Before'
 ./aruba/lib/aruba/platforms/local_environment.rb:22:in `call'
 ./aruba/lib/aruba/platforms/unix_platform.rb:78:in `with_environment'
 ./aruba/lib/aruba/api/core.rb:172:in `with_environment'
 ./aruba/lib/aruba/cucumber/hooks.rb:7:in `block in <top (required)>'
 /home/doudou/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
 /home/doudou/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
~~~

**Comment by mvz** [comment]
It seems the module containing the underlying method was deprecated in 0.11.0 already, but without any user-facing warnings.

**Comment by mvz** [comment]
This functionality is very useful and should be restored.

**Comment by maxmeyer** [comment]
@mvz This should give some context for the removal: 
* https://github.com/cucumber/aruba/pull/261
* https://github.com/cucumber/aruba/issues/315#issuecomment-156426255

**Comment by mvz** [comment]
@maxmeyer so your intention was to remove the `@disable-bundler` hook altogether and let people use `#delete_environment_variable` directly?

**Comment by maxmeyer** [comment]
I was not aware of this hook at that time. but yes, the idea was to avoid steps/methods which are tied to some tool or language. to make that vision clear I added the "our focus" and "our vision" section to the Readme.

**Comment by maxmeyer** [comment]
Unfortunately I had no clear "data" about uses of aruba. I even thought about asking the users what kind of language they use to see if the project has the correct focus. But unfortunately I didn't had the time to set it up properly.

**Comment by doudou** [comment]
> I was not aware of this hook at that time. but yes, the idea was to avoid steps/methods which are tied to some tool or language.

The problem with `@disable-bundler` is that the specificity of the "tool or language" is coming from Cucumber and Aruba themselves. Cucumber and Aruba are installed mostly with bundler, and therefore ends up in a bundler environment by the very nature of cucumber and aruba.

So ... how do you think this could work in my case ?

Basically, the issue I have is that I use aruba and cucumber to bootstrap [a robotic framework](https://rock-core.githu.io/rock-and-syskit), which internally uses some Ruby tools. This framework sets up a Bundler environment for itself to run the tools in.

So, I need to cleanup the caller's Bundler environment before I can spawn things in the callee. I guess I could reimplement `@disable-bundler` inside my environment, but it feels to me that *for ruby* `@disable-bundler` sounds like something that would make sense generically.

**Comment by mvz** [comment]
This has been fixed in master.
