### ISSUE TITLE
Executing relative paths, oh my!

### ISSUE THREAD

**Issue by mvz** [cucumber/aruba#552]
## Summary

Aruba looks for executables by relative path starting from the current directory, not from the working directory. This means a feature cannot create an executable and immediately run it. There are some corner cases that we need to think about

## Expected Behavior

A scenario like this should work:
```
    Feature: Run relative command

    Scenario: Run command
      Given an executable named "bin/local_cli" with:
      """
      #!/bin/bash
      exit 0
      """
      When I successfully run `bin/local_cli`
```

## Current Behavior

This fails with `Command "bin/local_cli" not found in PATH-variable`. This is because Aruba tries to find `bin/local_cli` in what Ruby thinks is the current directory (usually the project directory), rather than `aruba.current_directory`.

## Possible Solution

The radical solution is to look for relative executables in `aruba.current_directory`. I think this is the correct way, because:

* Executables that are part of the project under test are already available through the PATH, so using `bin/foo` for that does not make sense.
* `aruba.current_directory` represents where we 'are', during the running of a feature, and typing `bin/local_cli` there would resolve starting from that point.

**One problem may be projects that rely on the current broken behavior.**

## Context & Motivation

I'm trying to upgrade the aruba dependency for `rspec-rails`. That gem still depends on version `~> 0.5.4.`, probably because of this issue. My conclusion is that this is something that got broken between 0.5.4 and 0.14.x.

**Comment by mvz** [comment]
The first release where this was broken was `0.8.0`. It seems this is because earlier versions didn't check the presence of the executable using `#which` before attempting to run it.

**Comment by kennethkalmer** [comment]
I'm seeing the same in [daemon-kit](https://github.com/kennethkalmer/daemon-kit) after jumping from 0.5.3 to 0.14.x. In the case of daemon-kit I have the following steps that are failing:

```
Scenario: Using AMQP generator on an existing daemon # features/amqp_generator.feature:15
    Given I have an existing daemon called "vuvuzela"  # features/step_definitions/daemon_steps.rb:1
    And I cd to "vuvuzela"                             # aruba-0.14.5/lib/aruba/cucumber/file.rb:77
    When I run `./script/generate amqp` interactively  # aruba-0.14.5/lib/aruba/cucumber/command.rb:49
      Command "./script/generate" not found in PATH-variable "/Users/kenneth/Code/kennethkalmer/daemon-kit/bin:/Users/kenneth/Code/kennethkalmer/daemon-kit/exe:/usr/local/opt/rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bin:/usr/local/opt/rbenv/versions/2.4.2/bin:/usr/local/Cellar/rbenv/1.1.1/libexec:/Users/kenneth/.nvm/versions/node/v9.3.0/bin:/Users/kenneth/bin:/usr/local/opt/rbenv/shims:/usr/local/opt/rbenv/bin:/usr/local/bin:/usr/local/sbin:/Users/kenneth/.cargo/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/kenneth/Code/go/bin:/usr/local/opt/go/libexec/bin:/Users/kenneth/Code/FOSS/blackbox/bin". (Aruba::LaunchError)
      features/amqp_generator.feature:18:in `When I run `./script/generate amqp` interactively'
```

daemon-kit projects generate classic Rails-style generators (ala `./script/generate`) and these aren't in the path.
