### ISSUE TITLE
Appveyor tests fail on ENV['PATH']  being empty

### ISSUE THREAD

**Issue by olleolleolle** [cucumber/aruba#579]
## Summary

Looking at Appveyor tests failing, I noted that some of them were about `ENV['PATH']` was blank.

Can that be configured to fix it?

## Expected Behavior

No tests failing on Appveyor, would be nice.

## Current Behavior

Tests fail with `ENV['PATH']` not being set on Appveyor.

## Possible Solution

Configuring Appveyor builds to have a $PATH.

## Steps to Reproduce (for bugs)

n/a

## Context & Motivation

It keeps the build indicator red for all our PRs.

**Comment by luke-hill** [comment]
Update note for Developers. This currently (As of May 2019), accounts for ~30% of failures. 7/23 in a recent appveyor run

**Comment by mvz** [comment]
Two questions I have:
* Why would Appveyor not set $PATH!?
* Is some of this fixed by #505?

I can have a look at #505 next weekend and will also update the build set then; the rest of the failures are due to unsupported Ruby versions I think.

**Comment by luke-hill** [comment]
Given #505 has had 3 of you essentially mobbing on it. I suggest you get that merged in (If it's possible, as it's grown enormously), and then we re-check failures.

**Comment by mvz** [comment]
@luke-hill I've rebased #505 so we can get a fresh build and perhaps play around a bit with merging only part if that makes more sense. We'll see where this goes.

**Comment by mvz** [comment]
Closing this as we now have appveyor tests succeeding :tada:.

**Comment by olleolleolle** [comment]
So many congratulations!
