### ISSUE TITLE
Rethink bootstrap script

### ISSUE THREAD

**Issue by mvz** [cucumber/aruba#582]
## Summary

Investigate whether `bin/bootstrap`/`script/bootstrap` still makes sense and does the right thing.

## Expected Behavior

`bootstrap` needs to have significant advantages over the default gem development workflow (i.e., `bundle install`).

## Current Behavior

In addition to `bundle install`, `bootstrap` installs Bundler for you and checks that you have Ruby installed. These seem superfluous to me.

In `still`, `bootstrap` also checks for some external programs. I think these can be made optional, like in `master`.

## Possible Solution

Remove `bootstrap` and update the instructions accordingly.

## Context & Motivation

Use of `bootstrap` makes the Travis configuration more custom than it needs to be. Juggling its dual-use (setup of local environment, versus setup of CI environment) made fixing problems in #581 more complex.

**Comment by olleolleolle** [comment]
Remove the script, update docs: best solution here, I think.

**Comment by olleolleolle** [comment]
Fixed in #593.
