### ISSUE TITLE
exit false should result in exit_status 1

### ISSUE THREAD

**Issue by grosser** [cucumber/aruba#592]
When using Aruba::Processes::InProcess FakeKernel#exit does not translate false to 1, which results in `Then(/^the exit status should( not)? be (\d+)$/)` from `lib/aruba/cucumber/command.rb` to fail with ` has exit status of "1", but has "false"`

```
ruby -e 'exit false'
echo $?
1
```

so FakeKernel needs a fix ... I can do the PR if that sounds right.

**Comment by olleolleolle** [comment]
That _does_ sound right to me. A Ruby behavioural compatibility improvement to `FakeKernel`.
