### ISSUE TITLE
Windows newlines comes with carriage return

### ISSUE THREAD

**Issue by peagha** [cucumber/aruba#614]
## Summary

When comparing multiline strings in Windows, the comparison fails because of the carriage return.

## Expected Behavior

The comparison should work. like it does in Unix systems:
```
1 example, 0 failures
```

## Current Behavior

The comparison fails:
```
Failure/Error:
  expect(last_command_stopped.output).to include(<<~STR)
    a
    b
  STR

  expected "a\r\nb\r\n" to include "a\nb\n"
  Diff:
  @@ -1,2 +1,3 @@
  -a\nb\n
  +a
  +b
```

## Possible Solution

The issue is caused by the binmode in the tempfiles used for capturing the processes ouput:
https://github.com/cucumber/aruba/blob/add17615322f575588aef1fccce875396cdf36e9/lib/aruba/processes/spawn_process.rb#L79-L80

If I comment those lines, the comparison works because Ruby know how to handle the newline differences - it translates `\r\n` to `\n`. Using binmode is know to cause portability issues: https://www.rubytapas.com/2016/12/14/ruby-code-on-windows/

I don't know if disabling binmode causes other issues, but using a config to enable binmode will allow users to enable binmode if needed.

## Steps to Reproduce (for bugs)

I've created a repo that reproduces the problem: the suite works in Unix systems, but fails in Windows: https://github.com/peagha/aruba-windows-linebreak-issue

## Context & Motivation

I'm updating a book that uses Aruba for some exercises, and I want to ensure Windows users can follow the examples without the need to use a Unix system. I know Windows is not fully supported in Aruba, but fixing this issue is a step forward in that direction.

## Your Environment

* Version used: Aruba 0.14.9, Ruby 2.6.3
* Operating System and version: Windows 10 pro
* Link to your project: https://github.com/peagha/aruba-windows-linebreak-issue

**Comment by luke-hill** [comment]
@peagha would you feel confident submitting a PR you "think" remedies the situation.

We're looking into trying to fix up some of the windows issues and/or backporting them to a 0.14.x fix.

If you can push up a PR, we can see how it runs on Appveyor

**Comment by mvz** [comment]
@luke-hill I have disabled the stale bot so no need to use `slow burner` anymore :tada:.

**Comment by mvz** [comment]
@peagha if we can get by without binmode that would be the best.

**Comment by mvz** [comment]
Alright, I've looked at this and these are my findings/thoughts until now:
* We may be able to remove binmode, but then we have to set the encoding for these streams to ASCII-8BIT. That may be fine. Whether this problem will persist, I don't know.
* I wonder what happens if the Ruby file itself uses CR/LF line endings. I *think* I remember that Ruby will convert line endings in multi-line strings to LF characters, so this should be fine.
* Testing programs that emit binary on stdout will become tricky, so we need to add some way to handle that.
