### ISSUE TITLE
New alpha release downgraded my cucumber gem

### ISSUE THREAD

**Issue by jasnow** [cucumber/aruba#625]
Tried your new 1.0.0.pre.alpha.3 release and it took my cucumber gem from 
3.1.2 to 2.99.0. Appears one or more dependencies are holding it back.
Here is the diff of my Gemfile.lock file:

```
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -6,37 +6,31 @@ PATH
 GEM
   remote: https://rubygems.org/
   specs:
-    aruba (0.14.9)
-      childprocess (>= 0.6.3, < 1.1.0)
-      contracts (~> 0.9)
-      cucumber (>= 1.3.19)
+    aruba (1.0.0.pre.alpha.3)
+      childprocess (~> 1.0)
+      contracts (~> 0.13)
+      cucumber (~> 2.4)
       ffi (~> 1.9)
-      rspec-expectations (>= 2.99)
+      rspec-expectations (~> 3.4)
       thor (~> 0.19)
-    backports (3.15.0)
     builder (3.2.3)
     childprocess (1.0.1)
       rake (< 13.0)
     contracts (0.16.0)
-    cucumber (3.1.2)
+    cucumber (2.99.0)
       builder (>= 2.1.2)
-      cucumber-core (~> 3.2.0)
-      cucumber-expressions (~> 6.0.1)
+      cucumber-core (~> 1.5.0)
       cucumber-wire (~> 0.0.1)
-      diff-lcs (~> 1.3)
-      gherkin (~> 5.1.0)
+      diff-lcs (>= 1.1.3)
+      gherkin (~> 4.0)
       multi_json (>= 1.7.5, < 2.0)
       multi_test (>= 0.1.2)
-    cucumber-core (3.2.1)
-      backports (>= 3.8.0)
-      cucumber-tag_expressions (~> 1.1.0)
-      gherkin (~> 5.0)
-    cucumber-expressions (6.0.1)
-    cucumber-tag_expressions (1.1.1)
+    cucumber-core (1.5.0)
+      gherkin (~> 4.0)
     cucumber-wire (0.0.1)
     diff-lcs (1.3)
     ffi (1.11.0)
-    gherkin (5.1.0)
+    gherkin (4.1.3)
     json (2.2.0)
     minitest (5.11.3)
     multi_json (1.13.1)
@@ -52,7 +46,7 @@ PLATFORMS
   ruby

 DEPENDENCIES
-  aruba
+  aruba (= 1.0.0.pre.alpha.3)
   bundler
   cucumber
   json
```

**Comment by mvz** [comment]
Thanks, @jasnow. I'll look into it.

**Comment by mvz** [comment]
I'll release an alpha.4 soon.

**Comment by mvz** [comment]
@jasnow and released it is.

**Comment by jasnow** [comment]
@mvz - Tried alpha4. Should I make another issue regarding contracts (now at 0.16.0), ffi (now at 1.11.1), and rspec-expectations (now at 3.8.3) dependency constraints?

**Comment by mvz** [comment]
@jasnow Those constraints are like that on purpose so they allow both older and newer versions.

**Comment by jasnow** [comment]
Getting this error for **rake** on one of my repos after upgrading to alpha.4:
```
cannot load such file -- aruba/in_process (LoadError)
```
Run fine on current aruba gem release.

**Comment by mvz** [comment]
Hm .. that file is deprecated in the current release. Are you using the InProcess runner or just requiring that file somewhere?

**Comment by jasnow** [comment]
"in_process" still works (no error) in gem release 0.14.9.

**Comment by mvz** [comment]
That means you're not actually using the InProcess class defined there. I indeed noticed that requiring that file in 0.14.9 won't print a deprecation message, whereas instantiating Aruba::InProcess will. It probably should complain when required, but for using the alpha.4 release, you can just remove the require.

To help me find out where we need to improve deprecation messaging, do you know why you added a require for this particular file?

**Comment by jasnow** [comment]
Making a new issue starting with above comments to stop cluttering this issue.
