### ISSUE TITLE
Clean up step definitions

### ISSUE THREAD

**Issue by mvz** [cucumber/aruba#640]
## Summary

Some of Aruba's step definitions are very complex and have a lot of options. We should clean them up.

## Expected Behavior

Step definitions should be clear easy to follow.

## Current Behavior

Some step definitions have an awful lot of complex logic, making it hard to see what's going on. Especially when indirection is used to activate matchers.

## Possible Solution

We can at least split up some of the cases where the actions taken depend on some conditional based on a string literal.

## Context & Motivation

This came up in a pull request. See https://github.com/cucumber/aruba/pull/638#discussion_r289319924.

**Comment by luke-hill** [comment]
I'm gonna have a partial tackle at this, I saw a couple of places we could get some quick wins.

It won't close this issue out, but it'll definitely make some of the triaging a bit easier.
