### ISSUE TITLE
Aruba runtime error FFI

### ISSUE THREAD

**Issue by bcolferzd** [cucumber/aruba#648]
## Summary
Run time ffi error when running aruba init

## Expected Behavior
I expected the aruba to be intialized.

## Current Behavior
I’m running MacOS Mojave 10.14.5. I can gem install aruba with no errors but when I try aruba init I get:
/Users/me/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/me/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/ffi-1.9.17/lib/ffi_c.bundle, 9): Symbol not found: _ffi_type_double (LoadError)
Referenced from: /Users/me/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/ffi-1.9.17/lib/ffi_c.bundle
Expected in: flat namespace
in /Users/me/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/ffi-1.9.17/lib/ffi_c.bundle - /Users/me/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/ffi-1.9.17/lib/ffi_c.bundle
~~~
~~~

## Possible Solution
Fixing FFI?

## Steps to Reproduce (for bugs)
Run aruba init on Mojave 10.14.5
## Context & Motivation

I cannot use aruba on my new project.

## Your Environment

* Version used: aruba-0.14.10
* Operating System and version:MacOS Mojave 10.14.5 and Ruby 2.6.3

**Comment by mvz** [comment]
Hi @bcolferzd, this looks like a problem in the `ffi` gem. Can you also create an issue there? They can probably help you better. Please also link to that issue here so I can track it as well.

**Comment by bcolferzd** [comment]
Here is the solution:
https://github.com/ffi/ffi/issues/687#issuecomment-468005152
```
gem uninstall ffi
brew reinstall libffi
export LDFLAGS="-L/usr/local/opt/libffi/lib"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
gem install ffi
```
