### ISSUE TITLE
The 'append to file' steps should add newlines

### ISSUE THREAD

**Issue by luke-hill** [cucumber/aruba#662]
## Summary

Using `append to file` cuke, shouldn't cause
```
syntax error, unexpected end-of-input, expecting keyword_end (SyntaxError)
```

## Expected Behavior

It wouldn't cause the error above

## Current Behavior

It does cause the error above. Code similar to this can be produced

```
def path_to(page_name)
    self.send(page_name.split(' ').push('path').join('_').to_sym)
  end

  Then('I should see {string}') do |text|
    expect(page).to have_content(text)
  endWhen('I go to the session establish page') do # This is the problematic line
  visit path_to('session establish')
end
```

## Possible Solution

Check for newline characters. If one isn't found, add one.
Adding an extra newline even in the worst circumstance, is just a bad style, but not adding one can occassionally cause issues concatenating `end` and `Given` or `When` for example.

## Steps to Reproduce (for bugs)

1. Use cuke `write to file`
2. Use cuke `append to file` in the same scenario with an identical path
3.
4.

## Context & Motivation

This is present in both scenario and background -> scenario contexts.

I've tagged this as a bug because it does feel something that shouldn't happen

**Comment by mvz** [comment]
This seems to be due to missing carriage returns.

Do you have an example of how you're producing the bad output in your 'current behavior' section?

**Comment by luke-hill** [comment]
https://github.com/cucumber/cucumber-rails/pull/437/files#diff-c919fb7d9207732a01929e695d7c63baR87

**Comment by mvz** [comment]
This is due to how Cucumber handles these multi-line string parameters, which essentially amounts to it stripping exactly one newline. See https://github.com/cucumber/aruba/blob/dde73643e174f2e286f095219717783a6f26d097/features/03_testing_frameworks/cucumber/steps/filesystem/append_to_file.feature#L17 for the current scenario that shows this behavior. If you want a final newline in this step and in the write-to-file step, you need to add an empty line before the final `"""`.

I'm leaning towards simply pointing this behavior out more clearly in the documentation. WDYT?

**Comment by luke-hill** [comment]
I disagree, I think this is a bug that would need fixing.

When writing cukes, a lot of the descriptive websites / blogs don't have gaps between a Given and a When (I know you can have them), e.t.c.

I am in favour of just altering the logic to add a newline when using either of these aruba cukes (If one doesn't already exist). I'm happy to do the work in the next few days as well as I'm a little bit quiet this weekend.

**Comment by mvz** [comment]
The thing is, we would be altering the behavior of multi-line strings in cucumber scenarios; The removal of the final newline from these strings is simply how Gherkin works. If we change this for our steps, this would lead to inconsistencies and confusion. Also, it would make it impossible for users to append or create files without trailing newlines.

**Comment by luke-hill** [comment]
I disagree with that again. Although the point you raise about users cannot create/amend without newlines, this is valid. But I think this should be enforced - Files should always have a newline character at the end, else it causes issues, as encountered here.

Gherkin doesn't sanitize these strings because gherkin will parse each line accordingly, so there is a newline character being interpreted there.

**Comment by mvz** [comment]
> Gherkin doesn't sanitize these strings because gherkin will parse each line accordingly, so there is a newline character being interpreted there.

Aruba surely doesn't remove any trailing newlines, so it must be Cucumber/Gherkin doing it, right?

**Comment by luke-hill** [comment]
Those newlines are splitting the gherkin document into the relevant Lines, which then get converted into the AST's e.t.c.

It's a small bugfix I'm proposing to fix. I'm a bit confused for the lengthy debate, is there something I'm missing?

**Comment by mvz** [comment]
> I'm a bit confused for the lengthy debate, is there something I'm missing?

It's a breaking change, and I want to understand what's going on.

**Comment by luke-hill** [comment]
I mean, not really, yes it changes behaviour, but it's a defect? I'm really confused as to the confusion so to speak.

The descriptions / blogs / any resource I can find online doesn't show having extra lines in between each step in a feature (Same with us)

In order for us to work with aruba currently we have to pass in these phantom extra lines in weird places, so let's just fix the bug? It's a win-win.

**Comment by mvz** [comment]
Aruba's own scenarios show that this step allows appending without a newline appearing in the file, so we would be changing documented behavior. Hence, it's a breaking change.

I understand that this change would make it easier to construct cucumber feature files using Aruba, but other users may have different needs.

I'm trying to get at the bottom of this doc string behavior in Cucumber and Gherkin. Documentation that explained the behavior was removed at some point: https://github.com/cucumber/cucumber-ruby/blob/07a2421ea1ba9360737af8ee7c67d52d3e270f04/lib/cucumber/runtime/for_programming_languages.rb#L53. Once that's cleared up I can revisit this issue.

**Comment by luke-hill** [comment]
Should we fix this for 1.0?

**Comment by mvz** [comment]
No, I still don't think this is a bug.

**Comment by luke-hill** [comment]
Any thoughts still on this now 1.0 is cut? If we aren't going to fix this, we should mitigate this in cucumber-rails and document it accordingly.
