### ISSUE TITLE
Add run_script_string(:engine=> 'ruby', :cmd => string)

### ISSUE THREAD

**Issue by hedgehog** [cucumber/aruba#69]
Currently, you have to create a file, say `script_file`, then run `chmod +x script_file`, then call `run_simple("./script_file")`
Instead it would be useful to simply do:

```
cmd =<<-END_CMD.gsub(/^ {4}/, '')
  #!/usr/bin/env bash
  rvm gemset use vagrant
  cd #{vagrant.path}
  echo vagrant up #{vm_name}
  END_CMD
run_script_string(cmd)
stdout_from(cmd).should_not include(name)
```

of course the hash-bang could ruby etc.

In case it helps work out where any changes are required, the error you currently get:

```
    /home/hedge/.rvm/gems/ruby-1.9.2-p180@bbb_vm_monitor/gems/childprocess-0.1.8/lib/childprocess/unix/process.rb:92:in `exec': No such file or directory - #!/usr/bin/env (Errno::ENOENT)
from /home/hedge/.rvm/gems/ruby-1.9.2-p180@bbb_vm_monitor/gems/childprocess-0.1.8/lib/childprocess/unix/process.rb:92:in `block in launch_process'
from /home/hedge/.rvm/gems/ruby-1.9.2-p180@bbb_vm_monitor/gems/childprocess-0.1.8/lib/childprocess/unix/process.rb:83:in `fork'
from /home/hedge/.rvm/gems/ruby-1.9.2-p180@bbb_vm_monitor/gems/childprocess-0.1.8/lib/childprocess/unix/process.rb:83:in `launch_process'
from /home/hedge/.rvm/gems/ruby-1.9.2-p180@bbb_vm_monitor/gems/childprocess-0.1.8/lib/childprocess/abstract_process.rb:52:in `start'
from /home/hedge/.rvm/gems/ruby-1.9.2-p180@bbb_vm_monitor/gems/aruba-0.3.6/lib/aruba/process.rb:22:in `run!'
from /home/hedge/.rvm/gems/ruby-1.9.2-p180@bbb_vm_monitor/gems/aruba-0.3.6/lib/aruba/api.rb:212:in `block in run'
from /home/hedge/.rvm/gems/ruby-1.9.2-p180@bbb_vm_monitor/gems/aruba-0.3.6/lib/aruba/api.rb:9:in `chdir'
from /home/hedge/.rvm/gems/ruby-1.9.2-p180@bbb_vm_monitor/gems/aruba-0.3.6/lib/aruba/api.rb:9:in `in_current_dir'
from /home/hedge/.rvm/gems/ruby-1.9.2-p180@bbb_vm_monitor/gems/aruba-0.3.6/lib/aruba/api.rb:206:in `run'
from /home/hedge/.rvm/gems/ruby-1.9.2-p180@bbb_vm_monitor/gems/aruba-0.3.6/lib/aruba/api.rb:231:in `run_simple'
```

**Comment by AdrieanKhisbe** [comment]
@mattwynne Has this feature been implemented?
Or you are still welcoming such a patch :)

**Comment by mattwynne** [comment]
Not to my knowledge. I'm sure we'd still welcome a patch.

**Comment by AdrieanKhisbe** [comment]
Will then try to work and do some simular pull request :)

**Comment by dg-ratiodata** [comment]
@AdrieanKhisbe Is there any chance to make it more generic? Maybe something like this.

~~~ruby
generate 'path/to/file', actions: [:create, :run], content: content
~~~

@mattwynne What do you think? I'm not sure about the name for the method.

**Comment by dg-ratiodata** [comment]
@AdrieanKhisbe Ok. I just saw your PR. Is it correct, that you don't want to add more methods to the ruby API, but just want to add some more cucumber steps?

**Comment by AdrieanKhisbe** [comment]
I'm not opposed to that, but it seems more easy for me to combine and reuse existing steps.
Was enough to implement the functionality I wanted:I

 was interested in the cucumber steps, but indeed could be usefull to be accessible at a rspec level

**Comment by dg-ratiodata** [comment]
Mmmh... I'm a bit wary of adding methods to the API that only combines existing functionality to the ruby api so having only the cucumber steps is totally ok for me.
