### ISSUE TITLE
Run and stop command in before all RSpec hook

### ISSUE THREAD

**Issue by unrooty** [cucumber/aruba#706]
## Summary

Hello! I have a small question. Is it possible to `run_сommand_and_stop` in `before(:all)` RSpec hook and then use `last_command_started` to compare output?

## Expected Behavior

The following code should work.

```ruby
RSpec.describe 'Run', type: :aruba do
  before(:all) do
    run_command_and_stop('echo text')
  end
  
  it 'should work' do
    expect(last_command_started.output).to eq('text')
  end
end
```

## Current Behavior

Previous code raises the following exception:

```
Aruba::NoCommandHasBeenStartedError: No last command started available
```

**Comment by mvz** [comment]
No, this is not supported with a a `before :all` hook. Since the Aruba environment is reset before each spec, as soon as you have more than one spec, there would be no `last_command_started` in all but one of the specs.

It should work fine with `before :each`.

**Comment by unrooty** [comment]
Ok. But why the following behaviour doesn't work? Command is executed but the `@result` call causes the same error.

```ruby
before(:all) do
  run_command_and_stop('echo text')
  @result = last_command_started
  p @result.exit_status
end
```
Sorry for the stupid questions but I really don't fully understand whole cycle of Aruba work.

**Comment by mvz** [comment]
I would have expected that to work. I'll look into it.

**Comment by unrooty** [comment]
I was looking into it a little bit and it's look like there is some issue before in EventBus notification. So I don't understand why but looks like procs for commands execution are not registered in file lib/setup.rb in `before(:all)` case .

I mean this register events:

```ruby
runtime.event_bus.register(
  :command_stopped,
  proc do |event|
    runtime.command_monitor.last_command_stopped = event.entity
  end
)

runtime.event_bus.register(
  :command_stopped,
  proc do |event|
    runtime.command_monitor.last_command_stopped = event.entity
  end
)

```

**Comment by unrooty** [comment]
Also the simple workaround for `before(:all)` usage with Aruba is to create module with `self` methods like in module below, include it into RSpec, set first execution result in `before(:each)` hook and then check if it was set to prevent multiple command calls. 

For example the can create following module:
```ruby
# support/helpers/before_all.rb

module BeforeAllHelper
  def self.before_all_result
    @before_all_result
  end

  def self.before_all_result=(value)
    @before_all_result = value
  end
end
```

Then we need to include it into RSpec. 
**Note:** We need `before(:all)` hook to set previous result to `nil` to prevent results mixing.
```ruby
# spec_helper.rb

... # other requires

require_relative 'support/helpers/before_all'

RSpec.configure do |config|
  config.include BeforeAllHelper

  config.before(:all) do
    BeforeAllHelper.before_all_result = nil
  end
end
```

And finally we can use it in the following way:
```ruby
require 'spec_helper'

RSpec.describe 'Run', type: :aruba do
  before(:each) do
    unless BeforeAllHelper.before_all_result
      run_command_and_stop('echo text')
      BeforeAllHelper.before_all_result = last_command_started
    end

    @result = BeforeAllHelper.before_all_result
  end

  it 'should work' do
    expect(@result.output).to match('text')
  end

  it 'should exit with 0 status' do
    expect(@result.exit_status).to eq(0)
  end
end
```
Maybe this solution is not good and looks like a hack but it works fine and helps to make possible `before(:all)` like behaviour when we use Aruba.

**Comment by mvz** [comment]
I dug a little deeper into how Aruba sets things up for each spec. The reason this code doesn't work in a `before :all` hook is that Aruba sets up its environment in a `before :each` hook. This means the plumbing to make `last_command_started` work is just not present at the time your `before :all` block is executed.

Aruba should probably complain more if you try to use any of its commands before setup has taken place.

See [the documentation](https://app.cucumber.pro/p/af1681aa-415f-44f0-8260-5454a69c472a/aruba/documents/branch/master/features/03_testing_frameworks/rspec/setup_aruba_for_rspec.feature#scenario-custom-integration-using-beforeall-hook) for more information on how to set up Aruba for running commands inside a `before :all` hook.

**Comment by unrooty** [comment]
@mvz thank you for your work and for your answer! It helps a lot!
