### ISSUE TITLE
The append_to_file method should provide feedback if file does not exist

### ISSUE THREAD

**Issue by luke-hill** [cucumber/aruba#726]
## Summary

When using `When I append to file "...." with: ` one of the following should happen if the file doesn't exist.
- A warning should be thrown
- An error should be thrown

## Current Behavior

It silently does nothing

## Steps to Reproduce (for bugs)

Self explanatory

## Context & Motivation

Was fixing some stuff in cucumber-rails. Found this issue when writing some new features.

**Comment by mvz** [comment]
> It silently does nothing

What do you mean by this? From the code, it seems it silently creates the file. Is that the behavior you're seeing?

**Comment by mvz** [comment]
This is officially documented bad behavior: https://github.com/cucumber/aruba/blob/996d631d8baa6b447aef4d2d6543b482060b381e/features/03_testing_frameworks/cucumber/steps/filesystem/append_to_file.feature#L29-L43

Steps to resolve this:

- In 1.x: Deprecate silent creation of the file
- In 2.0: Remove silent creation of the file

**Comment by luke-hill** [comment]
Sounds perfect. Good solution, definite thumbs up from me.
