### ISSUE TITLE
Unable to activate aruba-1.0.4 Error

### ISSUE THREAD

**Issue by vasanthanpv** [cucumber/aruba#777]
## Summary
Im getting the below error while running the Ccucmber-Gherkin
**Unable to activate aruba-1.0.4, because childprocess-0.6.1 conflicts with childprocess (< 5.0, >= 2.0) (Gem::ConflictError**)
Installed the aruba gem for adding the below code in stepdefintions

Given /^a file named "([^"]*)" with:$/ do |file_name, file_content|
  write_file(file_name, file_content)
end
## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by mvz** [comment]
Aruba requires at least version 2.0 of childprocess so you cannot use it together with childprocess 0.6.1.

**Comment by vasanthanpv** [comment]
Thanks
 I m Using ,selenium-webdriver-3.142.0 it  depends on childprocess  0.6.1. If i remove childprocess 0.6.1 it will affect the selenium.Can anyone please suggest how to make it work.

**Comment by olleolleolle** [comment]
Perhaps you can update that gem to a later patch version of itself? https://rubygems.org/gems/selenium-webdriver/versions/3.142.7 allows a wider selection of childprocess?

`bundle update selenium-webdriver`

**Comment by vasanthanpv** [comment]
Thanks. After updating the childprocess to 2.0 and seleniumwebdriver to 3.142.7  The reported error gone and it is fixed.
