### ISSUE TITLE
Help request: Simulating Enter key in an interactive CLI

### ISSUE THREAD

**Issue by caalberts** [cucumber/aruba#807]
### Help request:

I'm writing a test for an interactive CLI that displays a list of options. The user can either press up/down arrow or Enter to select an option.

How can I do this using `aruba-rspec`?

**Comment by mvz** [comment]
@caalberts please follow the issue request template when filing issues. To get support, try https://community.smartbear.com/t5/Cucumber-Open/bd-p/CucumberOS or https://cucumberbdd.slack.com/
