### ISSUE TITLE
Rubydoc link is broken

### ISSUE THREAD

**Issue by adamdavis40208** [cucumber/aruba#826]
http://www.rubydoc.info/gems/aruba is in the readme. It's also on the rubygems page for gem documentation

**Comment by olleolleolle** [comment]
https://www.rubydoc.info/gems/~a/23

From what I can see this is the last visible page of gems of the letter A. That could indicate a troubled configuration of e.g. Elasticsearch.

**Comment by mvz** [comment]
It looks like this happened before: https://github.com/docmeta/rubydoc.info/issues/155

**Comment by mvz** [comment]
The gem is listed when you search for it: https://www.rubydoc.info/find/gems?q=aruba

**Comment by olleolleolle** [comment]
@mvz @adamdavis40208 Now the link has been restored by the maintenance team of Rubydoc. Thank you for letting us know!

Can this issue now be closed as fixed? I think so.

**Comment by mvz** [comment]
Yes, closing now.
